-- --------------------------------------------------------
-- Host:                         10.140.0.16
-- Versión del servidor:         8.0.36 - Source distribution
-- SO del servidor:              Linux
-- HeidiSQL Versión:             12.7.0.6850
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

-- Volcando estructura para tabla bodega.1_formularioweb
CREATE TABLE IF NOT EXISTS `1_formularioweb` (
  `id` int NOT NULL AUTO_INCREMENT,
  `fuente` varchar(1) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL,
  `codigo_prestador` text COLLATE utf8mb3_unicode_ci NOT NULL,
  `codigo_punto_atencion` text COLLATE utf8mb3_unicode_ci NOT NULL,
  `ano` smallint NOT NULL DEFAULT '0',
  `mes` tinyint NOT NULL DEFAULT '0',
  `tipo` varchar(50) COLLATE utf8mb3_unicode_ci NOT NULL,
  `prestador` mediumtext CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL,
  `departamento` mediumtext CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL,
  `municipio` mediumtext CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL,
  `punto` mediumtext CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL,
  `tot_personas_inscritas` int unsigned NOT NULL,
  `tot_personas_inscritas_hombres` int NOT NULL,
  `tot_personas_inscritas_mujeres` int NOT NULL DEFAULT '0',
  `tot_personas_inscritas_jovenes` int NOT NULL DEFAULT '0',
  `tot_personas_inscritas_mujeres_jovenes` int NOT NULL DEFAULT '0',
  `tot_personas_inscritas_hombres_jovenes` int NOT NULL DEFAULT '0',
  `tot_personas_inscritas_PcD` int NOT NULL DEFAULT '0',
  `tot_personas_inscritas_mujeres_PcD` int NOT NULL DEFAULT '0',
  `tot_personas_inscritas_hombres_PcD` int NOT NULL DEFAULT '0',
  `tot_personas_inscritas_Victimas` int NOT NULL DEFAULT '0',
  `tot_personas_inscritas_mujeres_victimas` int NOT NULL DEFAULT '0',
  `tot_personas_inscritas_hombres_victimas` int NOT NULL DEFAULT '0',
  `tot_personas_inscritas_migrantes` int NOT NULL DEFAULT '0',
  `tot_personas_inscritas_mujeres_migrantes` int NOT NULL DEFAULT '0',
  `tot_personas_inscritas_hombres_migrantes` int NOT NULL DEFAULT '0',
  `tot_personas_inscritas_grupo_etnico` int NOT NULL DEFAULT '0',
  `tot_personas_inscritas_mujeres_grupo_etnico` int NOT NULL DEFAULT '0',
  `tot_personas_inscritas_hombres_grupo_etnico` int NOT NULL DEFAULT '0',
  `remisiones_empleadores_tot` int NOT NULL DEFAULT '0',
  `remisiones_empleadores_hombres` int NOT NULL DEFAULT '0',
  `remisiones_empleadores_mujeres` int NOT NULL DEFAULT '0',
  `tot_remisiones_empleadores_victimas` int NOT NULL DEFAULT '0',
  `tot_remisiones_empleadores_mujeres_victimas` int NOT NULL DEFAULT '0',
  `tot_remisiones_empleadores_hombres_victimas` int NOT NULL DEFAULT '0',
  `tot_remisiones_empleadores_Pcd` int NOT NULL DEFAULT '0',
  `tot_remisiones_empleadores_mujeres_Pcd` int NOT NULL DEFAULT '0',
  `tot_remisiones_empleadores_hombres_Pcd` int NOT NULL DEFAULT '0',
  `tot_remisiones_empleadores_jovenes` int NOT NULL DEFAULT '0',
  `tot_remisiones_empleadores_mujeres_jovenes` int NOT NULL DEFAULT '0',
  `tot_remisiones_empleadores_hombres_jovenes` int NOT NULL DEFAULT '0',
  `tot_remisiones_empleadores_Migrantes` int NOT NULL DEFAULT '0',
  `tot_remisiones_empleadores_mujeres_Migrantes` int NOT NULL DEFAULT '0',
  `tot_remisiones_empleadores_hombres_Migrantes` int NOT NULL DEFAULT '0',
  `tot_remisiones_empleadores_Grupos_Etnicos` int NOT NULL DEFAULT '0',
  `tot_remisiones_empleadores_mujeres_Grupos_Etnicos` int NOT NULL DEFAULT '0',
  `tot_remisiones_empleadores_hombres_Grupos_Etnicos` int NOT NULL DEFAULT '0',
  `tot_colocados` int NOT NULL DEFAULT '0',
  `tot_colocados_hombres` int NOT NULL DEFAULT '0',
  `tot_colocados_mujeres` int NOT NULL DEFAULT '0',
  `tot_colocados_victimas` int NOT NULL DEFAULT '0',
  `tot_colocados_mujeres_victimas` int NOT NULL DEFAULT '0',
  `tot_colocados_hombres_victimas` int NOT NULL DEFAULT '0',
  `tot_colocados_PcD` int NOT NULL DEFAULT '0',
  `tot_colocados_mujeres_PcD` int NOT NULL DEFAULT '0',
  `tot_colocados_hombres_PcD` int NOT NULL DEFAULT '0',
  `tot_colocados_jovenes` int NOT NULL DEFAULT '0',
  `tot_colocados_mujeres_jovenes` int NOT NULL DEFAULT '0',
  `tot_colocados_hombres_jovenes` int NOT NULL DEFAULT '0',
  `tot_colocados_Migrantes` int NOT NULL DEFAULT '0',
  `tot_colocados_mujeres_Migrantes` int NOT NULL DEFAULT '0',
  `tot_colocados_hombres_Migrantes` int NOT NULL DEFAULT '0',
  `tot_colocados_grupo_etnico` int NOT NULL DEFAULT '0',
  `tot_colocados_mujeres_grupo_etnico` int NOT NULL DEFAULT '0',
  `tot_colocados_hombres_grupo_etnico` int NOT NULL DEFAULT '0',
  `tot_empleadores_inscritos` int NOT NULL DEFAULT '0',
  `tot_per_aten_entrev_atencion_ocupaci` int NOT NULL DEFAULT '0',
  `tot_per_aten_entrev_atencion_ocupaci_hombres` int NOT NULL DEFAULT '0',
  `tot_per_aten_entrev_atencion_ocupaci_mujeres` int NOT NULL DEFAULT '0',
  `tot_per_aten_entrev_atencion_ocupaci_victimas` int NOT NULL DEFAULT '0',
  `tot_per_aten_entrev_atencion_ocupaci_victimas_mujeres` int NOT NULL DEFAULT '0',
  `tot_per_aten_entrev_atencion_ocupaci_victimas_hombres` int NOT NULL DEFAULT '0',
  `tot_per_aten_entrev_atencion_ocupaci_Pcd` int NOT NULL DEFAULT '0',
  `tot_per_aten_entrev_atencion_ocupaci_Pcd_mujeres` int NOT NULL DEFAULT '0',
  `tot_per_aten_entrev_atencion_ocupaci_Pcd_hombres` int NOT NULL DEFAULT '0',
  `tot_per_aten_entrev_orienta_ocupaci_jovenes` int NOT NULL DEFAULT '0',
  `tot_per_aten_entrev_orienta_ocupaci_jovenes_mujeres` int NOT NULL DEFAULT '0',
  `tot_per_aten_entrev_orienta_ocupaci_jovenes_hombres` int NOT NULL DEFAULT '0',
  `tot_per_aten_entrev_orienta_ocupaci_Migrantes` int NOT NULL DEFAULT '0',
  `tot_per_aten_entrev_orienta_ocupaci_Migrantes_mujeres` int NOT NULL DEFAULT '0',
  `tot_per_aten_entrev_orienta_ocupaci_Migrantes_hombres` int NOT NULL DEFAULT '0',
  `tot_per_aten_entrev_orienta_ocupaci_grupo_etnico` int NOT NULL DEFAULT '0',
  `tot_per_aten_entrev_orienta_ocupaci_grupo_etnico_mujeres` int NOT NULL DEFAULT '0',
  `tot_per_aten_entrev_orienta_ocupaci_grupo_etnico_hombres` int NOT NULL DEFAULT '0',
  `tot_per_aten_activi_grup_orienta_ocupaci` int NOT NULL DEFAULT '0',
  `tot_per_aten_activi_grup_orienta_ocupaci_hombres` int NOT NULL DEFAULT '0',
  `tot_per_aten_activi_grup_orienta_ocupaci_mujeres` int NOT NULL DEFAULT '0',
  `tot_per_aten_activi_grup_orienta_ocupaci_jovenes` int NOT NULL DEFAULT '0',
  `tot_per_aten_activi_grup_orienta_ocupaci_jovenes_mujeres` int NOT NULL DEFAULT '0',
  `tot_per_aten_activi_grup_orienta_ocupaci_jovenes_hombres` int NOT NULL DEFAULT '0',
  `tot_per_aten_activi_grup_orienta_ocupaci_Pcd` int NOT NULL DEFAULT '0',
  `tot_per_aten_activi_grup_orienta_ocupaci_Pcd_mujeres` int NOT NULL DEFAULT '0',
  `tot_per_aten_activi_grup_orienta_ocupaci_Pcd_hombres` int NOT NULL DEFAULT '0',
  `tot_per_aten_activi_grup_orienta_ocupaci_victimas` int NOT NULL DEFAULT '0',
  `tot_per_aten_activi_grup_orienta_ocupaci_victimas_mujeres` int NOT NULL DEFAULT '0',
  `tot_per_aten_activi_grup_orienta_ocupaci_victimas_hombres` int NOT NULL DEFAULT '0',
  `tot_per_aten_activi_grup_orienta_ocupaci_migrantes` int NOT NULL DEFAULT '0',
  `tot_per_aten_activi_grup_orienta_ocupaci_migrantes_mujeres` int NOT NULL DEFAULT '0',
  `tot_per_aten_activi_grup_orienta_ocupaci_migrantes_hombres` int NOT NULL DEFAULT '0',
  `tot_per_aten_activi_grup_orienta_ocupaci_grupo_etnico` int NOT NULL DEFAULT '0',
  `tot_per_aten_activi_grup_orienta_ocupaci_grupo_etnico_mujeres` int NOT NULL DEFAULT '0',
  `tot_per_aten_activi_grup_orienta_ocupaci_grupo_etnico_hombres` int NOT NULL DEFAULT '0',
  `no_per_direc_progr_formac_y_capaci_par_el_trabajo` int NOT NULL DEFAULT '0',
  `no_per_direc_progr_formac_y_capaci_par_el_trabajo_hombres` int NOT NULL DEFAULT '0',
  `no_per_direc_progr_formac_compete_claves_y_trans_hombres` int NOT NULL DEFAULT '0',
  `no_per_direc_progr_formac_tecno_info_y_comunica_tic_hombres` int NOT NULL DEFAULT '0',
  `no_per_direc_progr_alfabetizacion_o_bachillerato_hombres` int NOT NULL DEFAULT '0',
  `no_per_direc_progr_entrevnamiento_o_reentre_técnico_hombres` int NOT NULL DEFAULT '0',
  `no_per_direc_progr_técnico_laboral_hombres` int NOT NULL DEFAULT '0',
  `no_per_direc_progr_formac_y_capaci_par_el_trabajo_mujeres` int NOT NULL DEFAULT '0',
  `no_per_direc_progr_formac_compete_claves_y_trans_mujeres` int NOT NULL DEFAULT '0',
  `no_per_direc_progr_formac_tecno_info_y_comunica_tic_mujeres` int NOT NULL DEFAULT '0',
  `no_per_direc_progr_alfabetizacion_o_bachillerato_mujeres` int NOT NULL DEFAULT '0',
  `no_per_direc_progr_entrevnamiento_o_reentre_técnico_mujeres` int NOT NULL DEFAULT '0',
  `no_per_direc_progr_técnico_laboral_mujeres` int NOT NULL DEFAULT '0',
  `no_per_que_culmi_progr_formac_y_capaci_par_el_trabajo` int NOT NULL DEFAULT '0',
  `no_per_que_culmi_progr_formac_y_capaci_par_el_trabajo_hombres` int NOT NULL DEFAULT '0',
  `no_per_que_culmi_progr_formac_compete_claves_y_trans_hombres` int NOT NULL DEFAULT '0',
  `no_per_que_culmi_progr_formac_tecno_info_y_comunica_tic_hombres` int NOT NULL DEFAULT '0',
  `no_per_que_culmi_progr_alfabetizacion_o_bachillerato_hombres` int NOT NULL DEFAULT '0',
  `no_per_que_culmi_progr_entrevnamiento_o_reentre_técnico_hombres` int NOT NULL DEFAULT '0',
  `no_per_que_culmi_progr_técnico_laboral_hombres` int NOT NULL DEFAULT '0',
  `no_per_que_culmi_progr_formac_y_capaci_par_el_trabajo_mujeres` int NOT NULL DEFAULT '0',
  `no_per_que_culmi_progr_formac_compete_claves_y_trans_mujeres` int NOT NULL DEFAULT '0',
  `no_per_que_culmi_progr_formac_tecno_info_y_comunica_tic_mujeres` int NOT NULL DEFAULT '0',
  `no_per_que_culmi_progr_alfabetizacion_o_bachillerato_mujeres` int NOT NULL DEFAULT '0',
  `no_per_que_culmi_progr_entrevnamiento_o_reentre_técnico_mujeres` int NOT NULL DEFAULT '0',
  `no_per_que_culmi_progr_técnico_laboral_mujeres` int NOT NULL DEFAULT '0',
  `tot_per_direc_progr_emprendimiento` int NOT NULL DEFAULT '0',
  `tot_per_direc_progr_emprendimiento_hombres` int NOT NULL DEFAULT '0',
  `tot_per_direc_progr_emprendimiento_mujeres` int NOT NULL DEFAULT '0',
  `tot_PQRS_radicados` int NOT NULL DEFAULT '0',
  `prestservicios_gestión_y_colocación_de_empleo_en_el_exterior` int NOT NULL DEFAULT '0',
  `tot_hojas_vid_remitidas_exterior` int NOT NULL DEFAULT '0',
  `tot_hojas_vid_remitidas_exterior_hombres` int NOT NULL DEFAULT '0',
  `tot_hojas_vid_remitidas_exterior_mujeres` int NOT NULL DEFAULT '0',
  `tot_per_colocadas_exterior` int NOT NULL DEFAULT '0',
  `tot_per_colocadas_exterior_hombres` int NOT NULL DEFAULT '0',
  `tot_per_colocadas_exterior_mujeres` int NOT NULL DEFAULT '0',
  `tot_empleadores_registrados_exterior` int NOT NULL DEFAULT '0',
  `tot_vacantes_registrados_exterior` int NOT NULL DEFAULT '0',
  `punto_atencion_correo` varchar(100) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `punto_atencion_direcion` varchar(150) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `punto_atencion_fechregistro` text COLLATE utf8mb3_unicode_ci,
  `observaciones` longtext COLLATE utf8mb3_unicode_ci,
  `coordinador_nombre` varchar(100) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `coordinador_correo` varchar(100) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `coordinador_telefono` text COLLATE utf8mb3_unicode_ci,
  `coordinador_celular` text COLLATE utf8mb3_unicode_ci,
  `responsable_nombre` varchar(150) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `responsable_correo` varchar(100) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `responsable_telefono` text COLLATE utf8mb3_unicode_ci,
  `responsable_celular` text COLLATE utf8mb3_unicode_ci,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci ROW_FORMAT=DYNAMIC;

-- Volcando datos para la tabla bodega.1_formularioweb: 0 rows
/*!40000 ALTER TABLE `1_formularioweb` DISABLE KEYS */;
/*!40000 ALTER TABLE `1_formularioweb` ENABLE KEYS */;

-- Volcando estructura para tabla bodega.2_sise
CREATE TABLE IF NOT EXISTS `2_sise` (
  `id` int NOT NULL AUTO_INCREMENT,
  `fuente` tinyint NOT NULL DEFAULT '0',
  `ID_PRESTADOR` text COLLATE utf8mb3_unicode_ci NOT NULL,
  `ID_PUNTO_ATENCIÓN` text COLLATE utf8mb3_unicode_ci NOT NULL,
  `AÑO` smallint NOT NULL DEFAULT '0',
  `MES` tinyint NOT NULL DEFAULT '0',
  `TIPO_PRESTADOR` varchar(255) COLLATE utf8mb3_unicode_ci NOT NULL,
  `PRESTADOR` varchar(255) COLLATE utf8mb3_unicode_ci NOT NULL,
  `DEPARTAMENTO` varchar(255) COLLATE utf8mb3_unicode_ci NOT NULL,
  `MUNICIPIO` varchar(255) COLLATE utf8mb3_unicode_ci NOT NULL,
  `DIRECCION` varchar(255) COLLATE utf8mb3_unicode_ci NOT NULL,
  `PERSONAS_INSCRITAS_NETO` int NOT NULL DEFAULT '0',
  `PERSONAS_INSCRITAS_TOTAL_ENTRADAS` int NOT NULL DEFAULT '0',
  `PERSONAS_INSCRITAS_TOTAL_SALIDAS` int NOT NULL DEFAULT '0',
  `PERSONAS_INSCRITAS_HOMBRES` int NOT NULL DEFAULT '0',
  `PERSONAS_INSCRITAS_MUJERES` int NOT NULL DEFAULT '0',
  `PERSONAS_INSCRITAS_TOTAL_SALIDAS_Mujer` int NOT NULL DEFAULT '0',
  `PERSONAS_INSCRITAS_TOTAL_SALIDAS_Hombre` int NOT NULL DEFAULT '0',
  `PERSONAS_INSCRITAS_TOTAL_SALIDAS_Victimas` int NOT NULL DEFAULT '0',
  `PERSONAS_INSCRITAS_TOTAL_SALIDAS_Victimas_mujeres` int NOT NULL DEFAULT '0',
  `PERSONAS_INSCRITAS_TOTAL_SALIDAS_Victimas_hombres` int NOT NULL DEFAULT '0',
  `PERSONAS_INSCRITAS_TOTAL_SALIDAS_discapacidad` int NOT NULL DEFAULT '0',
  `PERSONAS_INSCRITAS_TOTAL_SALIDAS_discapacidad_mujeres` int NOT NULL DEFAULT '0',
  `PERSONAS_INSCRITAS_TOTAL_SALIDAS_discapacidad_hombre` int NOT NULL DEFAULT '0',
  `PERSONAS_INSCRITAS_TOTAL_SALIDAS_de_18_a_28_años` int NOT NULL DEFAULT '0',
  `PERSONAS_INSCRITAS_TOTAL_SALIDAS_de_18_a_28_años_mujeres` int NOT NULL DEFAULT '0',
  `PERSONAS_INSCRITAS_TOTAL_SALIDAS_de_18_a_28_años_hombres` int NOT NULL DEFAULT '0',
  `REMISIONES_A_EMPLEADORES_TOTAL` int NOT NULL DEFAULT '0',
  `REMISIONES_A_EMPLEADORES_HOMBRES` int NOT NULL DEFAULT '0',
  `REMISIONES_A_EMPLEADORES_MUJERES` int NOT NULL DEFAULT '0',
  `REMISIONES_A_EMPLEADORES_VICTIMAS` int NOT NULL DEFAULT '0',
  `REMISIONES_A_EMPLEADORES_VICTIMAS_MUJERES` int NOT NULL DEFAULT '0',
  `REMISIONES_A_EMPLEADORES_VICTIMAS_HOMBRES` int NOT NULL DEFAULT '0',
  `REMISIONES_A_EMPLEADORES_PCD` int NOT NULL DEFAULT '0',
  `REMISIONES_A_EMPLEADORES_PCD_MUJERES` int NOT NULL DEFAULT '0',
  `REMISIONES_A_EMPLEADORES_PCD_HOMBRES` int NOT NULL DEFAULT '0',
  `REMISIONES_A_EMPLEADORES_DE_18_A_28_AÑOS` int NOT NULL DEFAULT '0',
  `REMISIONES_A_EMPLEADORES_DE_18_A_28_AÑOS_MUJERES` int NOT NULL DEFAULT '0',
  `REMISIONES_A_EMPLEADORES_DE_18_A_28_AÑOS_HOMBRES` int NOT NULL DEFAULT '0',
  `REMISIONES_A_EMPLEADORES_MIGRANTES_VENEZOLANOS` int NOT NULL DEFAULT '0',
  `REMISIONES_A_EMPLEADORES_MIGRANTES_VENEZOLANOS_HOMBRES` int NOT NULL DEFAULT '0',
  `REMISIONES_A_EMPLEADORES_MIGRANTES_VENEZOLANOS_MUJERES` int NOT NULL DEFAULT '0',
  `Total_Oferentes_Neto_Hombres` int NOT NULL DEFAULT '0',
  `Total_Oferentes_Neto_Mujeres` int NOT NULL DEFAULT '0',
  `Total_Oferentes_Neto_Victimas` int NOT NULL DEFAULT '0',
  `Total_Oferentes_Neto_Victimas_Mujeres` int NOT NULL DEFAULT '0',
  `Total_Oferentes_Neto_Victimas_Hombres` int NOT NULL DEFAULT '0',
  `Total_Oferentes_Neto_Discapacidad` int NOT NULL DEFAULT '0',
  `Total_Oferentes_Neto_Discapacidad_Mujeres` int NOT NULL DEFAULT '0',
  `Total_Oferentes_Neto_Discapacidad_Hombres` int NOT NULL DEFAULT '0',
  `Total_Oferentes_Neto_de_18_a_28_años` int NOT NULL DEFAULT '0',
  `Total_Oferentes_Neto_de_18_a_28_años_Mujeres` int NOT NULL DEFAULT '0',
  `Total_Oferentes_Neto_de_18_a_28_años_Hombres` int NOT NULL DEFAULT '0',
  `Total_Oferentes_Neto_Migrantes_Venezolanos` int NOT NULL DEFAULT '0',
  `Total_Oferentes_Neto_Migrantes_Venezolanos_Hombres` int NOT NULL DEFAULT '0',
  `Total_Oferentes_Neto_Migrantes_Venezolanos_Mujeres` int NOT NULL DEFAULT '0',
  `OFERENTES_AUTOPOSTULADOS` int NOT NULL DEFAULT '0',
  `OFERENTES_AUTOPOSTULADOS_HOMBRES` int NOT NULL DEFAULT '0',
  `OFERENTES_AUTOPOSTULADOS_MUJERES` int NOT NULL DEFAULT '0',
  `OFERENTES_AUTOPOSTULADOS_VICTIMAS` int NOT NULL DEFAULT '0',
  `OFERENTES_AUTOPOSTULADOS_VICTIMAS_HOMBRES` int NOT NULL DEFAULT '0',
  `OFERENTES_AUTOPOSTULADOS_VICTIMAS_MUJERES` int NOT NULL DEFAULT '0',
  `OFERENTES_AUTOPOSTULADOS_DE_18_A_28_AÑOS` int NOT NULL DEFAULT '0',
  `OFERENTES_AUTOPOSTULADOS_DE_18_A_28_AÑOS_HOMBRES` int NOT NULL DEFAULT '0',
  `OFERENTES_AUTOPOSTULADOS_DE_18_A_28_AÑOS_MUJERES` int NOT NULL DEFAULT '0',
  `OFERENTES_AUTOPOSTULADOS_DISCAPACIDAD` int NOT NULL DEFAULT '0',
  `OFERENTES_AUTOPOSTULADOS_DISCAPACIDAD_MUJERES` int NOT NULL DEFAULT '0',
  `OFERENTES_AUTOPOSTULADOS_DISCAPACIDAD_HOMBRES` int NOT NULL DEFAULT '0',
  `OFERENTES_AUTOPOSTULADOS_MIGRANTES_VENEZOLANOS` int NOT NULL DEFAULT '0',
  `OFERENTES_AUTOPOSTULADOS_MIGRANTES_VENEZOLANOS_HOMBRES` int NOT NULL DEFAULT '0',
  `OFERENTES_AUTOPOSTULADOS_MIGRANTES_VENEZOLANOS_MUJERES` int NOT NULL DEFAULT '0',
  `OFERENTES_REMITIDOS_POR_EL_PUNTO_DE_ATENCION` int NOT NULL DEFAULT '0',
  `OFERENTES_REMITIDOS_POR_AUTOPOSTULACION_ASISTIDA` int NOT NULL DEFAULT '0',
  `TOTAL_COLOCADOS` int NOT NULL DEFAULT '0',
  `COLOCADOS_ACTUALES` int NOT NULL DEFAULT '0',
  `COLOCADOS_DEVUELTOS` int NOT NULL DEFAULT '0',
  `COLOCADOS_DIRECTOS` int NOT NULL DEFAULT '0',
  `COLOCADOS_INDIRECTOS` int NOT NULL DEFAULT '0',
  `COLOCADOS_HOMBRES` int NOT NULL DEFAULT '0',
  `COLOCADOS_MUJERES` int NOT NULL DEFAULT '0',
  `EMPRESAS_SEDES_INSCRITAS_NETO` int NOT NULL DEFAULT '0',
  `EMPRESAS_SEDES_TOTAL_ENTRADAS` int NOT NULL DEFAULT '0',
  `EMPRESAS_SEDES_TOTAL_SALIDAS` int NOT NULL DEFAULT '0',
  `EMPRESAS_INSCRITAS` int NOT NULL DEFAULT '0',
  `SEDES_INSCRITAS` int NOT NULL DEFAULT '0',
  `VACANTES_REGISTRADAS_TOTAL` int NOT NULL DEFAULT '0',
  `PUESTOS_DE_TRABAJO` int NOT NULL DEFAULT '0',
  `PUESTOS_DE_TRABAJO_CON_GESTION` int NOT NULL DEFAULT '0',
  `PUESTOS_DE_TRABAJO_SIN_GESTION` int NOT NULL DEFAULT '0',
  `Total_Colocados_Indirectos_Hombres` int NOT NULL DEFAULT '0',
  `Total_Colocados_Indirectos_Mujeres` int NOT NULL DEFAULT '0',
  `Total_Colocados_Directos_Hombres` int NOT NULL DEFAULT '0',
  `Total_Colocados_Directos_Mujeres` int NOT NULL DEFAULT '0',
  `TOTAL_COLOCADOS_DIRECTOS_VICTIMAS` int NOT NULL DEFAULT '0',
  `TOTAL_COLOCADOS_DIRECTOS_VICTIMAS_MUJERES` int NOT NULL DEFAULT '0',
  `TOTAL_COLOCADOS_DIRECTOS_VICTIMAS_HOMBRE` int NOT NULL DEFAULT '0',
  `TOTAL_COLOCADOS_DIRECTOS_PCD` int NOT NULL DEFAULT '0',
  `TOTAL_COLOCADOS_DIRECTOS_PCD_MUJERES` int NOT NULL DEFAULT '0',
  `TOTAL_COLOCADOS_DIRECTOS_PCD_HOMBRE` int NOT NULL DEFAULT '0',
  `TOTAL_COLOCADOS_DIRECTOS_DE_18_A_28_AÑOS` int NOT NULL DEFAULT '0',
  `TOTAL_COLOCADOS_DIRECTOS_DE_18_A_28_AÑOS_MUJERES` int NOT NULL DEFAULT '0',
  `TOTAL_COLOCADOS_DIRECTOS_DE_18_A_28_AÑOS_HOMBRE` int NOT NULL DEFAULT '0',
  `TOTAL_COLOCADOS_DIRECTOS_MIGRANTES_VENEZOLANOS` int NOT NULL DEFAULT '0',
  `TOTAL_COLOCADOS_DIRECTOS_MIGRANTES_VENEZOLANOS_HOMBRE` int NOT NULL DEFAULT '0',
  `TOTAL_COLOCADOS_DIRECTOS_MIGRANTES_VENEZOLANOS_MUJERES` int NOT NULL DEFAULT '0',
  `Orientación_Laboral_Entrevistas` int NOT NULL DEFAULT '0',
  `Orientación_Laboral_Entrevistas_Hombres` int NOT NULL DEFAULT '0',
  `Orientación_Laboral_Entrevistas_Mujeres` int NOT NULL DEFAULT '0',
  `Orientación_Laboral_Entrevistas_victimas` int NOT NULL DEFAULT '0',
  `Orientación_Laboral_Entrevistas_victimas_mujeres` int NOT NULL DEFAULT '0',
  `Orientación_Laboral_Entrevistas_victimas_hombres` int NOT NULL DEFAULT '0',
  `Orientación_Laboral_Entrevistas_PcD` int NOT NULL DEFAULT '0',
  `Orientación_Laboral_Entrevistas_PcD_mujeres` int NOT NULL DEFAULT '0',
  `Orientación_Laboral_Entrevistas_PcD_hombres` int NOT NULL DEFAULT '0',
  `Orientación_Laboral_Entrevistas_de_18_a_28_años` int NOT NULL DEFAULT '0',
  `Orientación_Laboral_Entrevistas_18_a_28_mujeres` int NOT NULL DEFAULT '0',
  `Orientación_Laboral_Entrevistas_18_a_28_hombres` int NOT NULL DEFAULT '0',
  `Orientación_Laboral_Entrevistas_Migrantes_Venezolanos` int NOT NULL DEFAULT '0',
  `Orientación_Laboral_Entrevistas_Migrantes_Venezolanos_Mujeres` int NOT NULL DEFAULT '0',
  `Orientación_Laboral_Entrevistas_Migrantes_Venezolanos_Hombres` int NOT NULL DEFAULT '0',
  `Orientación_Laboral_Actividades_Grupales` int NOT NULL DEFAULT '0',
  `Orientación_Laboral_Actividades_Grupales_Hombres` int NOT NULL DEFAULT '0',
  `Orientación_Laboral_Actividades_Grupales_Mujeres` int NOT NULL DEFAULT '0',
  `Orientación_Laboral_Actividades_Grupales_Victimas` int NOT NULL DEFAULT '0',
  `Orientación_Laboral_Actividades_Grupales_Victimas_Mujeres` int NOT NULL DEFAULT '0',
  `Orientación_Laboral_Actividades_Grupales_Víctimas_Hombres` int NOT NULL DEFAULT '0',
  `Orientación_Laboral_Actividades_Grupales_Discapacidad` int NOT NULL DEFAULT '0',
  `Orientación_Laboral_Actividades_Grupales_Discapacidad_Mujeres` int NOT NULL DEFAULT '0',
  `Orientación_Laboral_Actividades_Grupales_Discapacidad_Hombres` int NOT NULL DEFAULT '0',
  `Orientación_Laboral_Actividades_Grupales_18_a_28_años` int NOT NULL DEFAULT '0',
  `Orientación_Laboral_Actividades_Grupales_18_a_28_años_Mujeres` int NOT NULL DEFAULT '0',
  `Orientación_Laboral_Actividades_Grupales_18_a_28_años_Hombres` int NOT NULL DEFAULT '0',
  `Talleres_Actividades_Grupales` int NOT NULL DEFAULT '0',
  `Talleres_Actividades_Grupales_Hombres` int NOT NULL DEFAULT '0',
  `Talleres_Actividades_Grupales_Mujeres` int NOT NULL DEFAULT '0',
  `Talleres_Actividades_Grupales_Migrantes_Venezolanos` int NOT NULL DEFAULT '0',
  `Talleres_Actividades_Grupales_Migrantes_Venezolanos_Mujeres` int NOT NULL DEFAULT '0',
  `Talleres_Actividades_Grupales_Migrantes_Venezolanos_Hombres` int NOT NULL DEFAULT '0',
  `Capacitación_Registrados` int NOT NULL DEFAULT '0',
  `Capacitación_Registrados_Hombres` int NOT NULL DEFAULT '0',
  `Capacitación_Registrados_alfabetización_bachillerato_Hombres` int NOT NULL DEFAULT '0',
  `Capacitación_Registrados_Competen_claves_trasversales_Hombres` int NOT NULL DEFAULT '0',
  `Capacitación_Registrados_Curso_Seminario_Diplomado_Hombres` int NOT NULL DEFAULT '0',
  `Capacitación_Registrados_Técnico_Laboral_Hombres` int NOT NULL DEFAULT '0',
  `Capacitación_Registrados_TICS_Hombres` int NOT NULL DEFAULT '0',
  `Capacitación_Registrados_Mujeres` int NOT NULL DEFAULT '0',
  `Capacitación_Registrados_alfabetización_bachillerato_Mujeres` int NOT NULL DEFAULT '0',
  `Capacitación_Registrados_Competen_claves_trasversales_Mujeres` int NOT NULL DEFAULT '0',
  `Capacitación_Registrados_Curso_Seminario_Diplomado_Mujeres` int NOT NULL DEFAULT '0',
  `Capacitación_Registrados_Técnico_Laboral_Mujeres` int NOT NULL DEFAULT '0',
  `Capacitación_Registrados_TICS_Mujeres` int NOT NULL DEFAULT '0',
  `Capacitación_Finalizados` int NOT NULL DEFAULT '0',
  `Capacitación_Finalizados_Hombres` int NOT NULL DEFAULT '0',
  `Capacitación_Finalizados_alfabetización_bachillerato_Hombres` int NOT NULL DEFAULT '0',
  `Capacitación_Finalizados_Competen_claves_trasversales_Hombres` int NOT NULL DEFAULT '0',
  `Capacitación_Finalizados_Curso_Seminario_Diplomado_Hombres` int NOT NULL DEFAULT '0',
  `Capacitación_Finalizados_Técnico_Laboral_Hombres` int NOT NULL DEFAULT '0',
  `Capacitación_Finalizados_TICS_Hombres` int NOT NULL DEFAULT '0',
  `Capacitación_Finalizados_Mujeres` int NOT NULL DEFAULT '0',
  `Capacitación_Finalizados_alfabetización_bachillerato_Mujeres` int NOT NULL DEFAULT '0',
  `Capacitación_Finalizados_Competen_claves_trasversales_Mujeres` int NOT NULL DEFAULT '0',
  `Capacitación_Finalizados_Curso_Seminario_Diplomado_Mujeres` int NOT NULL DEFAULT '0',
  `Capacitación_Finalizados_Técnico_Laboral_Mujeres` int NOT NULL DEFAULT '0',
  `Capacitación_Finalizados_TICS_Mujeres` int NOT NULL DEFAULT '0',
  `Emprendimiento_Registrados` int NOT NULL DEFAULT '0',
  `Emprendimiento_Registrados_Curso_Diplomado_Otro_Hombres` int NOT NULL DEFAULT '0',
  `Emprendimiento_Registrados_Curso_Diplomado_Otro_Mujeres` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci ROW_FORMAT=DYNAMIC;

-- Volcando datos para la tabla bodega.2_sise: 0 rows
/*!40000 ALTER TABLE `2_sise` DISABLE KEYS */;
/*!40000 ALTER TABLE `2_sise` ENABLE KEYS */;

-- Volcando estructura para tabla bodega.3_sena
CREATE TABLE IF NOT EXISTS `3_sena` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `fuente` tinyint NOT NULL,
  `ID_PUNTO_AT` text COLLATE utf8mb3_unicode_ci NOT NULL,
  `MES` tinyint NOT NULL DEFAULT '0',
  `AÑO` smallint NOT NULL DEFAULT '0',
  `pais` int NOT NULL,
  `DPT_ID` int NOT NULL,
  `DEPARTAMENTO` varchar(255) COLLATE utf8mb3_unicode_ci NOT NULL,
  `MPO_ID` int NOT NULL,
  `MUNICIPIO` varchar(255) COLLATE utf8mb3_unicode_ci NOT NULL,
  `INSCRITOS_MUJER` bigint NOT NULL,
  `INSCRITOS_HOMBRE` bigint NOT NULL,
  `INSCRITOS_JOVENES_MUJER` bigint NOT NULL,
  `INSCRITOS_JOVENES_HOMBRE` bigint NOT NULL,
  `INSCRITOS_PCD_MUJER` bigint NOT NULL,
  `INSCRITOS_PCD_HOMBRE` bigint NOT NULL,
  `INSCRITOS_RUV_MUJER` bigint NOT NULL,
  `INSCRITOS_RUV_HOMBRE` bigint NOT NULL,
  `ORIENTADOS_MUJER_IND` bigint NOT NULL,
  `ORIENTADOS_MUJER_GRU` int NOT NULL,
  `ORIENTADOS_HOMBRE_IND` int NOT NULL,
  `ORIENTADOS_HOMBRE_GRU` int NOT NULL,
  `ORIENTADOS_JOVENES_MUJER_IND` int NOT NULL,
  `ORIENTADOS_JOVENES_MUJER_GRU` int NOT NULL,
  `ORIENTADOS_JOVENES_HOMBRE_IND` int NOT NULL,
  `ORIENTADOS_JOVENES_HOMBRE_GRU` int NOT NULL,
  `ORIENTADOS_PCD_MUJER_IND` int NOT NULL,
  `ORIENTADOS_PCD_MUJER_GRU` int NOT NULL,
  `ORIENTADOS_PCD_HOMBRE_IND` int NOT NULL,
  `ORIENTADOS_PCD_HOMBRE_GRU` int NOT NULL,
  `ORIENTADOS_RUV_MUJER_IND` int NOT NULL,
  `ORIENTADOS_RUV_MUJER_GRU` int NOT NULL,
  `ORIENTADOS_RUV_HOMBRE_IND` int NOT NULL,
  `ORIENTADOS_RUV_HOMBRE_GRU` int NOT NULL,
  `COLOCACIONES_MUJER` int NOT NULL,
  `COLOCACIONES_HOMBRE` int NOT NULL,
  `COLOCACIONES_JOVENES_MUJER` int NOT NULL,
  `COLOCACIONES_JOVENES_HOMBRE` int NOT NULL,
  `COLOCACIONES_PCD_MUJER` int NOT NULL,
  `COLOCACIONES_PCD_HOMBRE` int NOT NULL,
  `COLOCACIONES_RUV_MUJER` int NOT NULL,
  `COLOCACIONES_RUV_HOMBRE` int NOT NULL,
  `POSTULACIONES_MUJER_ASISTIDA` int NOT NULL,
  `POSTULACIONES_MUJER_AUTO` int NOT NULL,
  `POSTULACIONES_HOMBRE_ASISTIDA` int NOT NULL,
  `POSTULACIONES_HOMBRE_AUTO` int NOT NULL,
  `POSTS_JOVENES_MUJER_ASISTIDA` int NOT NULL,
  `POSTS_JOVENES_HOMBRE_ASISTIDA` int NOT NULL,
  `POSTS_JOVENES_MUJER_AUTO` int NOT NULL,
  `POSTS_JOVENES_HOMBRE_AUTO` int NOT NULL,
  `POSTS_PCD_MUJER_ASISTIDA` int NOT NULL,
  `POSTS_PCD_MUJER_AUTO` int NOT NULL,
  `POSTS_PCD_HOMBRE_ASISTIDA` int NOT NULL,
  `POSTS_PCD_HOMBRE_AUTO` int NOT NULL,
  `POSTS_RUV_MUJER_ASISTIDA` int NOT NULL,
  `POSTS_RUV_MUJER_AUTO` int NOT NULL,
  `POSTS_RUV_HOMBRE_ASISTIDA` int NOT NULL,
  `POSTS_RUV_HOMBRE_AUTO` int NOT NULL,
  `EMPRESAS` int NOT NULL,
  `SOLICITUDES` int NOT NULL,
  `VACANTES` int NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci ROW_FORMAT=DYNAMIC;

-- Volcando datos para la tabla bodega.3_sena: 0 rows
/*!40000 ALTER TABLE `3_sena` DISABLE KEYS */;
/*!40000 ALTER TABLE `3_sena` ENABLE KEYS */;

-- Volcando estructura para tabla bodega.4_base
CREATE TABLE IF NOT EXISTS `4_base` (
  `id` int NOT NULL AUTO_INCREMENT,
  `fuente` tinyint NOT NULL,
  `id_punto` int NOT NULL,
  `id_prestador_cipres` int NOT NULL,
  `nit` varchar(20) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `prestador` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `departamento` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `municipio` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `divipola` int DEFAULT NULL,
  `direccion_punto_de_atencion` text COLLATE utf8mb4_general_ci,
  `departamento_asociado_a_la_url` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `divipola_asociada_a_la_url` int DEFAULT NULL,
  `segunda_direccion` text COLLATE utf8mb4_general_ci,
  `convenio` text COLLATE utf8mb4_general_ci,
  `tipo_de_prestador` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `naturaleza_del_prestador_publico_privado` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `clase_de_prestador` text COLLATE utf8mb4_general_ci,
  `tipo_de_ccf` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `clase_ente_territorial` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `modalidad_de_prestacion_del_servicio` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `tipo_de_punto_de_atencion` text COLLATE utf8mb4_general_ci NOT NULL,
  `modalidad_de_prestación_del_servicio` varchar(255) COLLATE utf8mb4_general_ci NOT NULL,
  `municipios_que_recorre_la_estrategia_movil` text COLLATE utf8mb4_general_ci,
  `pagina_web` text COLLATE utf8mb4_general_ci,
  `nombre_del_representante_legal` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `tipo_de_documento` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `numero_de_identificacion` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `correo_electronico_representante_legal` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `telefono_representante_legal` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `celular_representante_legal` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `direccion_de_correspondencia` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `coordinador_principal` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `tipo_de_documento_coordinador_principal` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `cedula_coordinador_principal` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `telefono_coordinador_principal` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `celular_coordinador_principal` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `correo_coordinador_principal` text COLLATE utf8mb4_general_ci,
  `coordinador_punto_de_atencion` text COLLATE utf8mb4_general_ci,
  `tipo_de_documento_coordinador` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `numero_de_identificacion_coordinador` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `telefono_de_contacto_coordinador_punto_de_atencion` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `celular_coordinador_punto_de_atencion` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `correo_electronico_coordinador_punto_de_atencion` text COLLATE utf8mb4_general_ci,
  `correo_eelectronico_punto_de_atencion` text COLLATE utf8mb4_general_ci,
  `telefono_punto_de_atencion` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `autorizacion` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `operacion` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `registro` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `orientacion` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `preseleccion` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `remision` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `cobros_servicios_basicos_si_no` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `otros_servicios` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `asociados` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `adicionales` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `cobros_especializados_si` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `observaciones` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `horario_de_punto_de_atencion` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `resolucion_es_de_autorizacion` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `fechas_de_resoluciones_de_autorizacion` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `resolucion_de_modificacion` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `fecha_de_resolucion_de_modificacion` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `resolucion_de_negacion` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `fecha_de_resolucion_de_negacion` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `resolucion_de_desistimiento` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `fecha_de_resolucion_de_desistimiento` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `resolucion_de_recursos` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `fecha_de_resolucion_de_recursos` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `resolucion_de_revocaroria` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `fecha_de_resolucion_de_revocaroria` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `resolucion_de_aclaracion_o_correccion_error` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `fecha_de_resolucion_de_aclaracion_o_correccion_error` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `otras_resoluciones` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `fecha_de_otras_resoluciones` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `resolución_vigente` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `fecha_de_resolucion_vigente` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `fecha_de_notificacion_de_resolucion` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `fecha_ejecutoria_de_resolucion` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `fecha_de_inicio_de_vigencia_de_resolucion` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `fecha_de_expiracion_resolucion` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `fecha_expiración_de_resolucion_con_decreto_491` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `compania_de_seguro_poliza` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `fecha_expedicion_poliza` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `fecha_vencimiento_poliza` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `estado_de_la_poliza` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `fecha_de_insercion` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `fecha_de_actualizacion` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `transnacional` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `sise` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `tramites_administrativos_sancionatorios` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `auto_existencia_merito` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `auto_de_apertura` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `auto_de_cierre` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `acto_administrativo_primera_instancia` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `resuelve_recurso_reposicion_primera_instancia` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `acto_administrativo_segunda_instancia` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `conducta_ejercicio_irregular_inobservancia_de_los_principios` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `sancion_impuesta` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `oficios_de_comunicacion_a_prestador` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Volcando datos para la tabla bodega.4_base: ~0 rows (aproximadamente)

-- Volcando estructura para tabla bodega.archivos
CREATE TABLE IF NOT EXISTS `archivos` (
  `id` int NOT NULL AUTO_INCREMENT,
  `nombre` varchar(200) COLLATE utf16_spanish_ci NOT NULL,
  `fecha` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf16 COLLATE=utf16_spanish_ci;

-- Volcando datos para la tabla bodega.archivos: 0 rows
/*!40000 ALTER TABLE `archivos` DISABLE KEYS */;
/*!40000 ALTER TABLE `archivos` ENABLE KEYS */;

-- Volcando estructura para tabla bodega.fuentes
CREATE TABLE IF NOT EXISTS `fuentes` (
  `id_fuente` tinyint(1) NOT NULL AUTO_INCREMENT,
  `nombre` varchar(50) COLLATE utf16_spanish_ci NOT NULL,
  PRIMARY KEY (`id_fuente`)
) ENGINE=MyISAM AUTO_INCREMENT=6 DEFAULT CHARSET=utf16 COLLATE=utf16_spanish_ci;

-- Volcando datos para la tabla bodega.fuentes: 4 rows
/*!40000 ALTER TABLE `fuentes` DISABLE KEYS */;
INSERT INTO `fuentes` (`id_fuente`, `nombre`) VALUES
	(3, 'SENA'),
	(2, 'SISE'),
	(1, 'Formulario Web'),
	(4, 'Base de Caracterizacion');
/*!40000 ALTER TABLE `fuentes` ENABLE KEYS */;

-- Volcando estructura para tabla bodega.login
CREATE TABLE IF NOT EXISTS `login` (
  `id` int NOT NULL AUTO_INCREMENT,
  `nombre` varchar(200) COLLATE utf16_spanish_ci NOT NULL,
  `correo` varchar(200) COLLATE utf16_spanish_ci NOT NULL,
  `clave` mediumtext COLLATE utf16_spanish_ci NOT NULL,
  `recuperar` varchar(10) COLLATE utf16_spanish_ci NOT NULL,
  `tipo` tinyint NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=13 DEFAULT CHARSET=utf16 COLLATE=utf16_spanish_ci;

-- Volcando datos para la tabla bodega.login: 2 rows
/*!40000 ALTER TABLE `login` DISABLE KEYS */;
INSERT INTO `login` (`id`, `nombre`, `correo`, `clave`, `recuperar`, `tipo`) VALUES
	(1, 'Pablo Carreño', 'pablo.carreno@serviciodeempleo.gov.co', '123456', 'pl', 1),
	(12, 'Johanna Gisella Reyes', 'johanna.reyes@serviciodeempleo.gov.co', '2024', 'pl', 1);
/*!40000 ALTER TABLE `login` ENABLE KEYS */;

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
