const { connection } = require("../database")
const util = require("util");

const query = util.promisify(connection.query).bind(connection);

const fetchConsolidadoData = async (month = "", year = "") => {
    try {
		const getQuery = (monthTable, yearTable) => {
			const conditions = [];

			if (month !== "") {
			 	conditions.push(`${monthTable} = '${month}'`);
			}
			if (year !== "") {
			  	conditions.push(`${yearTable} = '${year}'`);
			}

			return conditions.length > 0 ? `WHERE ${conditions.join(' AND ')}` : '';
		};

		const tabla1 = await query(`SELECT * FROM 1_formularioweb ${getQuery("mes", "ano")}`)
		const tabla2 = await query(`SELECT * FROM 2_sise ${getQuery("MES", "AÑO")}`);
		const tabla3 = await query(`SELECT * FROM 3_sena ${getQuery("MES", "AÑO")}`);
        const tabla4 = await query("SELECT * FROM 4_base");

        // Convertir los resultados de las tablas en objetos indexados por el código del punto de atención
        const indexedTabla1 = indexBy(tabla1, 'codigo_punto_atencion');
        const indexedTabla2 = indexBy(tabla2, 'ID_PUNTO_ATENCIÓN');
        const indexedTabla3 = indexBy(tabla3, 'ID_PUNTO_AT');
        const indexedTabla4 = indexTable4By(tabla4, 'id_punto');

        // Unir los datos de las tablas 1 y 2 con la tabla 4
        const registrosFinales = joinTables(indexedTabla1, indexedTabla2, indexedTabla3, indexedTabla4);

        return registrosFinales;

    } catch (err) {
        // console.error(err);
        throw new Error(err);
    }
};

// Función para indexar un array de objetos por una propiedad específica
const indexTable4By = (array, property) => {
    return array.reduce((acc, obj) => {
        acc[obj[property]] = obj;
        return acc;
    }, {});
};
const indexBy = (array, property) => {
    return array.reduce((acc, obj) => {
        const key = obj[property];
        if (!acc[key]) {
            acc[key] = [obj];
        } else {
            acc[key].push(obj);
        }
        return acc;
    }, {});
};

// Función para unir los datos de las tablas 1 y 2 con la tabla 4
const joinTables = (tabla1, tabla2, tabla3, tabla4) => {
    const registrosFinales = [];

    // Iterar sobre los registros de la tabla 1
	for (const codigoPuntoAtencion of Object.keys(tabla1)) {
		const registrosTabla1 = tabla1[codigoPuntoAtencion];

		const tablaBase = tabla4[codigoPuntoAtencion] || {};

		// Unir datos de las tablas 1 y 4
		for (const registroTabla1 of registrosTabla1) {
			const registroFinal = {
				ID_PUNTO_AT: registroTabla1.codigo_punto_atencion,
				ID_PRESTAD: tablaBase.id_prestador_cipres || null,
				AÑO: registroTabla1.ano,
				MES: registroTabla1.mes,
				Marcacion_Sistema: registroTabla1.fuente,
				ID_PRESTADOR: tablaBase.id_prestador_cipres || null,
				Divipola_Departamento: tablaBase.divipola_asociada_a_la_url || null,
				Divipola_Municipio: tablaBase.divipola || null,
				TIPO_PRESTADOR: tablaBase.tipo_de_prestador || null,
				PRESTADOR: tablaBase.prestador || null,
				DEPARTAMENTO: tablaBase.departamento || null,
				MUNICIPIO: tablaBase.municipio || null,
				CONCACTENAR: tablaBase.departamento || null + tablaBase.municipio || null,
				CIUDAD_CAPITAL: null,
				DIRECCION: registroTabla1.punto_atencion_direcion,
				TIPO_PUNTO_DE_ATENCIoN: tablaBase.tipo_de_punto_de_atencion || null,

				TOTAL_INSCRITOS_NETO_SISE_1_numero_de_personas_inscritas_registradas_CV: registroTabla1.tot_personas_inscritas,
				TOTAL_INSCRITOS_NETO_HOMBRES_SISE_1_numero_de_personas_inscritas_registradas_CV: registroTabla1.tot_personas_inscritas_hombres,
				TOTAL_INSCRITOS_NETO_MUJERES_SISE_1_numero_de_personas_inscritas_registradas_CV: registroTabla1.tot_personas_inscritas_mujeres,
				TOTAL_INSCRITOS_ENTRADAS_SISE_1_numero_de_personas_inscritas_registradas_CV: registroTabla1.tot_personas_inscritas,
				TOTAL_INSCRITOS_HOMBRES_ENTRADAS_SISE_1_1_numero_de_personas_inscritas_registradas_hombres_CV: registroTabla1.tot_personas_inscritas_hombres,
				TOTAL_INSCRITOS_MUJERES_ENTRADAS_SISE_1_2_numero_de_personas_inscritas_registradas_mujeres_CV: registroTabla1.tot_personas_inscritas_mujeres,
				TOTAL_INSCRITOS_SALIDAS_SISE: null,
				TOTAL_INSCRITOS_JoVENES_SISE: registroTabla1.tot_personas_inscritas_jovenes,
				TOTAL_INSCRITOS_JoVENES_MUJERES_SISE: registroTabla1.tot_personas_inscritas_mujeres_jovenes,
				TOTAL_INSCRITOS_JoVENES_HOMBRES_SISE: registroTabla1.tot_personas_inscritas_hombres_jovenes,
				TOTAL_INSCRITOS_PcD_SISE: registroTabla1.tot_personas_inscritas_PcD,
				TOTAL_INSCRITOS_PcD_MUJERES_SISE: registroTabla1.tot_personas_inscritas_mujeres_PcD,
				TOTAL_INSCRITOS_PcD_HOMBRES_SISE: registroTabla1.tot_personas_inscritas_hombres_PcD,
				TOTAL_INSCRITOS_VICTIMAS_SISE: registroTabla1.tot_personas_inscritas_Victimas,
				TOTAL_INSCRITOS_VICTIMAS_MUJERES_SISE: registroTabla1.tot_personas_inscritas_mujeres_victimas,
				TOTAL_INSCRITOS_VICTIMAS_HOMBRES_SISE: registroTabla1.tot_personas_inscritas_hombres_victimas,
				Total_Oferentes_Neto_Migrantes_Venezolanos: registroTabla1.tot_personas_inscritas_migrantes,
				Total_Oferentes_Neto_Migrantes_Venezolanos_Mujeres: registroTabla1.tot_personas_inscritas_mujeres_migrantes,
				Total_Oferentes_Neto_Migrantes_Venezolanos_Hombres: registroTabla1.tot_personas_inscritas_hombres_migrantes,
				TOTAL_OFERENTES_ETNICOS: registroTabla1.tot_personas_inscritas_grupo_etnico,
				TOTAL_OFERENTES_ETNICOS_MUJERES: registroTabla1.tot_personas_inscritas_mujeres_grupo_etnico,
				TOTAL_OFERENTES_ETNICOS_HOMBRES: registroTabla1.tot_personas_inscritas_hombres_grupo_etnico,
				REMISIONES_A_EMPLEADORES_TOTAL_SISE_2_numero_de_hojas_de_vida_remitidas_a_empleadores_CV: null,
				REMISIONES_A_EMPLEADORES_HOMBRES_SISE_2_1_numero_de_hojas_de_vida_remitidas_a_empleadores_hombres_CV: null,
				REMISIONES_A_EMPLEADORES_MUJERES_SISE_2_2_numero_de_hojas_de_vida_remitidas_a_empleadores_mujeres_CV: null,
				AUTOPOSTULADOS_SISE: null,
				OFERENTES_AUTOPOSTULADOS_HOMBRES: null,
				OFERENTES_AUTOPOSTULADOS_MUJERES: null,
				OFERENTES_JoVENES_AUTOPOSTULADOS: null,
				OFERENTES_JoVENES_AUTOPOSTULADOS_MUJERES: null,
				OFERENTES_JoVENES_AUTOPOSTULADOS_HOMBRES: null,
				OFERENTES_PcD_AUTOPOSTULADOS: null,
				OFERENTES_PcD_AUTOPOSTULADOS_MUJERES: null,
				OFERENTES_PcD_AUTOPOSTULADOS_HOMBRES: null,
				OFERENTES_VICTIMAS_AUTOPOSTULADOS: null,
				OFERENTES_VICTIMAS_AUTOPOSTULADOS_MUJERES: null,
				OFERENTES_VICTIMAS_AUTOPOSTULADOS_HOMBRES: null,
				OFERENTES_AUTOPOSTULADOS_MIGRANTES_VENEZOLANOS: null,
				OFERENTES_AUTOPOSTULADOS_MIGRANTES_VENEZOLANOS_MUJERES: null,
				OFERENTES_AUTOPOSTULADOS_MIGRANTES_VENEZOLANOS_HOMBRES: null,
				REMITIDOS_A_EMPLEADORES_SIN_AUTOPOSTULADOS_SISE_2_numero_de_hojas_de_vida_remitidas_a_empleadores_CV: registroTabla1.remisiones_empleadores_tot,
				REMITIDOS_A_EMPLEADORES_SIN_AUTOPOSTULADOS_HOMBRES_SISE_2_1_numero_de_hojas_de_vida_remitidas_a_empleadores_hombres_CV: registroTabla1.remisiones_empleadores_hombres,
				_REMITIDOS_A_EMPLEADORES_SIN_AUTOPOSTULADOS_MUJERES_SISE_2_2_numero_de_hojas_de_vida_remitidas_a_empleadores_mujeres_CV: registroTabla1.remisiones_empleadores_mujeres,
				HOJAS_DE_VIDA_REMITIDAS_DIRECTAMENTE_POR_EL_PUNTO_DE_ATENCIoN: registroTabla1.remisiones_empleadores_tot,
				HOJAS_DE_VIDA_REMITIDAS_DIRECTAMENTE_POR_EL_PUNTO_DE_ATENCIoN_HOMBRES: registroTabla1.remisiones_empleadores_hombres,
				HOJAS_DE_VIDA_REMITIDAS_DIRECTAMENTE_POR_EL_PUNTO_DE_ATENCIoN_MUJERES: registroTabla1.remisiones_empleadores_mujeres,
				REMITIDOS_POR_EL_PUNTO_DE_ATENCIoN_TOTAL_SISE: registroTabla1.remisiones_empleadores_tot,
				REMITIDOS_POR_AUTOPOSTULACIoN_ASISTIDA_TOTAL_SISE_2_numero_de_hojas_de_vida_remitidas_a_empleadores_CV: registroTabla1.remisiones_empleadores_tot,
				TOTAL_REMISIONES_A_EMPLEADORES_VICTIMAS: registroTabla1.tot_remisiones_empleadores_victimas,
				TOTAL_REMISIONES_A_EMPLEADORES_VICTIMAS_MUJERES: registroTabla1.tot_remisiones_empleadores_mujeres_victimas,
				TOTAL_REMISIONES_A_EMPLEADORES_VICTIMAS_HOMBRES: registroTabla1.tot_remisiones_empleadores_hombres_victimas,
				REMISIONES_A_EMPLEADORES_VICTIMAS: registroTabla1.tot_remisiones_empleadores_victimas,
				REMISIONES_A_EMPLEADORES_VICTIMAS_MUJERES: registroTabla1.tot_remisiones_empleadores_mujeres_victimas,
				REMISIONES_A_EMPLEADORES_VICTIMAS_HOMBRES: registroTabla1.tot_remisiones_empleadores_hombres_victimas,
				TOTAL_REMISIONES_A_EMPLEADORES_PCD: registroTabla1.tot_remisiones_empleadores_Pcd,
				TOTAL_REMISIONES_A_EMPLEADORES_PCD_MUJERES: registroTabla1.tot_remisiones_empleadores_mujeres_Pcd,
				TOTAL_REMISIONES_A_EMPLEADORES_PCD_HOMBRES: registroTabla1.tot_remisiones_empleadores_hombres_Pcd,
				REMISIONES_A_EMPLEADORES_PCD: registroTabla1.tot_remisiones_empleadores_Pcd,
				REMISIONES_A_EMPLEADORES_PCD_MUJERES: registroTabla1.tot_remisiones_empleadores_mujeres_Pcd,
				REMISIONES_A_EMPLEADORES_PCD_HOMBRES: registroTabla1.tot_remisiones_empleadores_hombres_Pcd,
				TOTAL_REMISIONES_A_EMPLEADORES_DE_18_A_28_AÑOS: registroTabla1.tot_remisiones_empleadores_jovenes,
				TOTAL_REMISIONES_A_EMPLEADORES_DE_18_A_28_AÑOS_MUJERES: registroTabla1.tot_remisiones_empleadores_mujeres_jovenes,
				TOTAL_REMISIONES_A_EMPLEADORES_DE_18_A_28_AÑOS_HOMBRES: registroTabla1.tot_remisiones_empleadores_hombres_jovenes,
				REMISIONES_A_EMPLEADORES_DE_18_A_28_AÑOS: registroTabla1.tot_remisiones_empleadores_jovenes,
				REMISIONES_A_EMPLEADORES_DE_18_A_28_AÑOS_MUJERES: registroTabla1.tot_remisiones_empleadores_mujeres_jovenes,
				REMISIONES_A_EMPLEADORES_DE_18_A_28_AÑOS_HOMBRES: registroTabla1.tot_remisiones_empleadores_hombres_jovenes,
				TOTAL_REMISIONES_A_EMPLEADORES_MIGRANTES_VENEZOLANOS: registroTabla1.tot_remisiones_empleadores_Migrantes,
				TOTAL_REMISIONES_A_EMPLEADORES_MIGRANTES_VENEZOLANOS_MUJERES: registroTabla1.tot_remisiones_empleadores_mujeres_Migrantes,
				TOTAL_REMISIONES_A_EMPLEADORES_MIGRANTES_VENEZOLANOS_HOMBRES: registroTabla1.tot_remisiones_empleadores_hombres_Migrantes,
				REMISIONES_A_EMPLEADORES_MIGRANTES_VENEZOLANOS: registroTabla1.tot_remisiones_empleadores_Migrantes,
				REMISIONES_A_EMPLEADORES_MIGRANTES_VENEZOLANOS_MUJERES: registroTabla1.tot_remisiones_empleadores_mujeres_Migrantes,
				REMISIONES_A_EMPLEADORES_MIGRANTES_VENEZOLANOS_HOMBRES: registroTabla1.tot_remisiones_empleadores_hombres_Migrantes,
				REMISIONES_A_EMPLEADORES_ETNICOS: registroTabla1.tot_remisiones_empleadores_Grupos_Etnicos,
				REMISIONES_A_EMPLEADORES_ETNICOS_MUJERES: registroTabla1.tot_remisiones_empleadores_mujeres_Grupos_Etnicos,
				REMISIONES_A_EMPLEADORES_ETNICOS_HOMBRES: registroTabla1.tot_remisiones_empleadores_hombres_Grupos_Etnicos,
				TOTAL_COLOCADOS_SISE_3_numero_de_personas_colocadas_CV: registroTabla1.tot_colocados,
				COLOCADOS_ENTRADAS_SISE_3_numero_de_personas_colocadas_CV: registroTabla1.tot_colocados,
				COLOCADOS_DEVUELTOS_SISE: null,
				COLOCADOS_HOMBRES_SISE_3_1_numero_de_personas_colocadas_hombres_CV: registroTabla1.tot_colocados_hombres,
				COLOCADOS_MUJERES_SISE_3_2_numero_de_personas_colocadas_mujeres_CV: registroTabla1.tot_colocados_mujeres,
				COLOCADOS_DIRECTOS_SISE_3_numero_de_personas_colocadas_CV: registroTabla1.tot_colocados,
				COLOCADOS_DIRECTOS_HOMBRES_SISE_3_1_numero_de_personas_colocadas_hombres_CV: registroTabla1.tot_colocados_hombres,
				COLOCADOS_DIRECTOS_MUJERES_SISE_3_2_numero_de_personas_colocadas_mujeres_CV: registroTabla1.tot_colocados_mujeres,
				COLOCADOS_INDIRECTOS_SISE: null,
				COLOCADOS_INDIRECTOS_HOMBRES_SISE: null,
				COLOCADOS_INDIRECTOS_MUJERES_SISE: null,
				COLOCADOS_DIRECTOS_VICTIMAS_SISE: registroTabla1.tot_colocados_victimas,
				COLOCADOS_DIRECTOS_VICTIMAS_MUJERES_SISE: registroTabla1.tot_colocados_mujeres_victimas,
				COLOCADOS_DIRECTOS_VICTIMAS_HOMBRES_SISE: registroTabla1.tot_colocados_hombres_victimas,
				COLOCADOS_DIRECTOS_PcD_SISE: registroTabla1.tot_colocados_PcD,
				COLOCADOS_DIRECTOS_PcD_MUJERES_SISE: registroTabla1.tot_colocados_mujeres_PcD,
				COLOCADOS_DIRECTOS_PcD_HOMBRES_SISE: registroTabla1.tot_colocados_hombres_PcD,
				COLOCADOS_DIRECTOS_18_A_28_AÑOS_SISE: registroTabla1.tot_colocados_jovenes,
				COLOCADOS_DIRECTOS_18_A_28_AÑOS_MUJERES_SISE: registroTabla1.tot_colocados_mujeres_jovenes,
				COLOCADOS_DIRECTOS_18_A_28_AÑOS_HOMBRES_SISE: registroTabla1.tot_colocados_hombres_jovenes,
				COLOCADOS_DIRECTOS_MIGRANTES_VENEZOLANOS: registroTabla1.tot_colocados_Migrantes,
				COLOCADOS_DIRECTOS_MIGRANTES_VENEZOLANOS_MUJERES: registroTabla1.tot_colocados_mujeres_Migrantes,
				COLOCADOS_DIRECTOS_MIGRANTES_VENEZOLANOS_HOMBRE: registroTabla1.tot_colocados_hombres_Migrantes,
				COLOCADOS_DIRECTOS_ETNICOS: registroTabla1.tot_colocados_grupo_etnico,
				COLOCADOS_DIRECTOS_ETNICOS_MUJERES: registroTabla1.tot_colocados_mujeres_grupo_etnico,
				COLOCADOS_DIRECTOS_ETNICOS_HOMBRES: registroTabla1.tot_colocados_hombres_grupo_etnico,
				SEDES_INSCRITAS_TOTAL_NETO_SISE_4_numero_de_empleadores_registrados_inscritos_CV: registroTabla1.tot_empleadores_inscritos,
				SEDES_INSCRITAS_ENTRADAS_SISE_4_numero_de_empleadores_registrados_inscritos_CV: registroTabla1.tot_empleadores_inscritos,
				SEDES_INSCRITAS_SALIDAS_SISE: registroTabla1.tot_empleadores_inscritos,
				EMPRESAS_INSCRITAS_SISE_4_numero_de_empleadores_registrados_inscritos_CV: registroTabla1.tot_empleadores_inscritos,
				DIRECCIONAMIENTOS_INDIVIDUALES_DE_ORIENTACIoN_LABORAL_REALIZADOS_SISE_5_numero_de_personas_atendidas_en_entrevistas_de_orientacion_ocupacional_CV: registroTabla1.tot_per_aten_entrev_atencion_ocupaci,
				DIRECCIONAMIENTOS_INDIVIDUALES_DE_ORIENTACIoN_LABORAL_REALIZADOS_HOMBRES_SISE_5_1_numero_de_personas_atendidas_en_entrevistas_de_orientacion_ocupacional_hombres_CV: registroTabla1.tot_per_aten_entrev_atencion_ocupaci_hombres,
				DIRECCIONAMIENTOS_INDIVIDUALES_DE_ORIENTACIoN_LABORAL_REALIZADOS_MUJERES_SISE_5_2_numero_de_personas_atendidas_en_entrevistas_de_orientacion_ocupacional_mujeres_CV: registroTabla1.tot_per_aten_entrev_atencion_ocupaci_mujeres,
				VICTIMAS_DIRECCIONAMIENTOS_INDIVIDUALES_DE_ORIENTACIoN_LABORAL_SISE: registroTabla1.tot_per_aten_entrev_atencion_ocupaci_victimas,
				VICTIMAS_DIRECCIONAMIENTOS_INDIVIDUALES_DE_ORIENTACIoN_LABORAL_Mujeres_SISE: registroTabla1.tot_per_aten_entrev_atencion_ocupaci_victimas_mujeres,
				VICTIMAS_DIRECCIONAMIENTOS_INDIVIDUALES_DE_ORIENTACIoN_LABORAL_Hombres_SISE: registroTabla1.tot_per_aten_entrev_atencion_ocupaci_victimas_hombres,
				PCD_DIRECCIONAMIENTOS_INDIVIDUALES_DE_ORIENTACIoN_LABORAL_SISE: registroTabla1.tot_per_aten_entrev_atencion_ocupaci_Pcd,
				PCD_DIRECCIONAMIENTOS_INDIVIDUALES_DE_ORIENTACIoN_LABORAL_Mujeres_SISE: registroTabla1.tot_per_aten_entrev_atencion_ocupaci_Pcd_mujeres,
				PCD_DIRECCIONAMIENTOS_INDIVIDUALES_DE_ORIENTACIoN_LABORAL_Hombres_SISE: registroTabla1.tot_per_aten_entrev_atencion_ocupaci_Pcd_hombres,
				_18_a_28_AÑOS_DIRECCIONAMIENTOS_INDIVIDUALES_DE_ORIENTACIoN_LABORAL_SISE: registroTabla1.tot_per_aten_entrev_orienta_ocupaci_jovenes,
				_18_a_28_AÑOS_DIRECCIONAMIENTOS_INDIVIDUALES_DE_ORIENTACIoN_LABORAL_Mujeres_SISE: registroTabla1.tot_per_aten_entrev_orienta_ocupaci_jovenes_mujeres,
				_18_a_28_AÑOS_DIRECCIONAMIENTOS_INDIVIDUALES_DE_ORIENTACIoN_LABORAL_Hombres_SISE: registroTabla1.tot_per_aten_entrev_orienta_ocupaci_jovenes_hombres,
				MIGRANTES_VENEZOLANOS_DIRECCIONAMIENTOS_INDIVIDUALES_DE_ORIENTACIoN_LABORAL_SISE: registroTabla1.tot_per_aten_entrev_orienta_ocupaci_Migrantes,
				MIGRANTES_VENEZOLANOS_DIRECCIONAMIENTOS_INDIVIDUALES_DE_ORIENTACIoN_LABORAL_Mujeres_SISE: registroTabla1.tot_per_aten_entrev_orienta_ocupaci_Migrantes_mujeres,
				MIGRANTES_VENEZOLANOS_DIRECCIONAMIENTOS_INDIVIDUALES_DE_ORIENTACIoN_LABORAL_Hombres_SISE: registroTabla1.tot_per_aten_entrev_orienta_ocupaci_Migrantes_hombres,
				ETNICOS_DIRECCIONAMIENTOS_INDIVIDUALES_DE_ORIENTACIoN_LABORAL_SISE: registroTabla1.tot_per_aten_entrev_orienta_ocupaci_grupo_etnico,
				ETNICOS_MUJERES_DIRECCIONAMIENTOS_INDIVIDUALES_DE_ORIENTACIoN_LABORAL_SISE: registroTabla1.tot_per_aten_entrev_orienta_ocupaci_grupo_etnico_mujeres,
				ETNICOS_HOMBRES_DIRECCIONAMIENTOS_INDIVIDUALES_DE_ORIENTACIoN_LABORAL_SISE: registroTabla1.tot_per_aten_entrev_orienta_ocupaci_grupo_etnico_hombres,
				DIRECCIONAMIENTOS_GRUPALES_DE_ORIENTACIoN_LABORAL_REALIZADOS_SISE_6_numero_de_personas_atendidas_en_actividades_grupales_de_orientacion_ocupacional: registroTabla1.tot_per_aten_activi_grup_orienta_ocupaci,
				DIRECCIONAMIENTOS_GRUPALES_DE_ORIENTACIoN_LABORAL_REALIZADOS_HOMBRES_SISE_6_1_numero_de_personas_atendidas_en_actividades_grupales_de_orientacion_ocupacional_hombres: registroTabla1.tot_per_aten_activi_grup_orienta_ocupaci_hombres,
				DIRECCIONAMIENTOS_GRUPALES_DE_ORIENTACIoN_LABORAL_REALIZADOS_MUJERES_SISE_6_2_numero_de_personas_atendidas_en_actividades_grupales_de_orientacion_ocupacional_mujeres: registroTabla1.tot_per_aten_activi_grup_orienta_ocupaci_mujeres,
				DIRECCIONAMIENTOS_GRUPALES_DE_ORIENTACIoN_LABORAL_REALIZADOS_A_PERSONAS_18_a_28_AÑOS: registroTabla1.tot_per_aten_activi_grup_orienta_ocupaci_jovenes,
				DIRECCIONAMIENTOS_GRUPALES_DE_ORIENTACIoN_LABORAL_REALIZADOS_A_PERSONAS_18_a_28_AÑOS_MUJERES: registroTabla1.tot_per_aten_activi_grup_orienta_ocupaci_jovenes_mujeres,
				DIRECCIONAMIENTOS_GRUPALES_DE_ORIENTACIoN_LABORAL_REALIZADOS_A_PERSONAS_18_a_28_AÑOS_HOMBRES: registroTabla1.tot_per_aten_activi_grup_orienta_ocupaci_jovenes_hombres,
				DIRECCIONAMIENTOS_GRUPALES_DE_ORIENTACIoN_LABORAL_REALIZADOS_A_PcD: registroTabla1.tot_per_aten_activi_grup_orienta_ocupaci_Pcd,
				DIRECCIONAMIENTOS_GRUPALES_DE_ORIENTACIoN_LABORAL_REALIZADOS_A_PcD_MUJERES: registroTabla1.tot_per_aten_activi_grup_orienta_ocupaci_Pcd_mujeres,
				DIRECCIONAMIENTOS_GRUPALES_DE_ORIENTACIoN_LABORAL_REALIZADOS_A_PcD_HOMBRES: registroTabla1.tot_per_aten_activi_grup_orienta_ocupaci_Pcd_hombres,
				DIRECCIONAMIENTOS_GRUPALES_DE_ORIENTACIoN_LABORAL_REALIZADOS_A_VICTIMAS: registroTabla1.tot_per_aten_activi_grup_orienta_ocupaci_victimas,
				DIRECCIONAMIENTOS_GRUPALES_DE_ORIENTACIoN_LABORAL_REALIZADOS_A_VICTIMAS_MUJERES: registroTabla1.tot_per_aten_activi_grup_orienta_ocupaci_victimas_mujeres,
				DIRECCIONAMIENTOS_GRUPALES_DE_ORIENTACIoN_LABORAL_REALIZADOS_A_VICTIMAS_HOMBRES: registroTabla1.tot_per_aten_activi_grup_orienta_ocupaci_victimas_hombres,
				DIRECCIONAMIENTOS_GRUPALES_DE_ORIENTACIoN_LABORAL_REALIZADOS_A_Migrantes_Venezolanos: registroTabla1.tot_per_aten_activi_grup_orienta_ocupaci_migrantes,
				DIRECCIONAMIENTOS_GRUPALES_DE_ORIENTACIoN_LABORAL_REALIZADOS_A_Migrantes_Venezolanos_MUJERES: registroTabla1.tot_per_aten_activi_grup_orienta_ocupaci_migrantes_mujeres,
				DIRECCIONAMIENTOS_GRUPALES_DE_ORIENTACIoN_LABORAL_REALIZADOS_A_Migrantes_Venezolanos_HOMBRES: registroTabla1.tot_per_aten_activi_grup_orienta_ocupaci_migrantes_hombres,
				DIRECCIONAMIENTOS_GRUPALES_DE_ORIENTACIoN_LABORAL_REALIZADOS_A_ETNICOS: registroTabla1.tot_per_aten_activi_grup_orienta_ocupaci_grupo_etnico,
				DIRECCIONAMIENTOS_GRUPALES_DE_ORIENTACIoN_LABORAL_REALIZADOS_A_ETNICOS_MUJERES: registroTabla1.tot_per_aten_activi_grup_orienta_ocupaci_grupo_etnico_mujeres,
				DIRECCIONAMIENTOS_GRUPALES_DE_ORIENTACIoN_LABORAL_REALIZADOS_A_ETNICOS_HOMBRES: registroTabla1.tot_per_aten_activi_grup_orienta_ocupaci_grupo_etnico_hombres,
				DIRECCIONAMIENTOS_A_FORMACIoN_PARA_EL_TRABAJO_SISE_7_numero_de_personas_direccionadas_a_programas_de_formacion_y_capacitacion_para_el_trabajo: registroTabla1.no_per_direc_progr_formac_y_capaci_par_el_trabajo,
				_7_1_numero_de_personas_direccionadas_a_programas_de_formacion_y_capacitacion_para_el_trabajo_hombres: registroTabla1.no_per_direc_progr_formac_y_capaci_par_el_trabajo_hombres,
				_7_1_1_numero_de_personas_direccionadas_a_programas_de_formacion_en_competencias_claves_y_transversales_hombres: registroTabla1.no_per_direc_progr_formac_compete_claves_y_trans_hombres,
				_7_1_2_numero_de_personas_direccionadas_a_programas_de_formacion_en_tecnologias_de_la_informacion_y_las_comunicaciones_tic_hombres: registroTabla1.no_per_direc_progr_formac_tecno_info_y_comunica_tic_hombres,
				_7_1_3_numero_de_personas_direccionadas_a_programas_de_alfabetizacion_o_bachillerato_hombres: registroTabla1.no_per_direc_progr_alfabetizacion_o_bachillerato_hombres,
				_7_1_4_numero_de_personas_direccionadas_a_programas_de_entrenamiento_o_reentrenamiento_tecnico_hombres: registroTabla1.no_per_direc_progr_entrevnamiento_o_reentre_técnico_hombres,
				_7_1_5_numero_de_personas_direccionadas_a_programas_de_tecnico_laboral_hombres: registroTabla1.no_per_direc_progr_técnico_laboral_hombres,
				_7_2_numero_de_personas_direccionadas_a_programas_de_formacion_y_capacitacion_para_el_trabajo_mujeres: registroTabla1.no_per_direc_progr_formac_y_capaci_par_el_trabajo_mujeres,
				_7_2_1_numero_de_personas_direccionadas_a_programas_de_formacion_en_competencias_claves_y_transversales_mujeres: registroTabla1.no_per_direc_progr_formac_compete_claves_y_trans_mujeres,
				_7_2_2_numero_de_personas_direccionadas_a_programas_de_formacion_en_tecnologias_de_la_informacion_y_las_comunicaciones_tic_mujeres: registroTabla1.no_per_direc_progr_formac_tecno_info_y_comunica_tic_mujeres,
				_7_2_3_numero_de_personas_direccionadas_a_programas_de_alfabetizacion_o_bachillerato_mujeres: registroTabla1.no_per_direc_progr_alfabetizacion_o_bachillerato_mujeres,
				_7_2_4_numero_de_personas_direccionadas_a_programas_de_entrenamiento_o_reentrenamiento_tecnico_mujeres: registroTabla1.no_per_direc_progr_entrevnamiento_o_reentre_técnico_mujeres,
				_7_2_5_numero_de_personas_direccionadas_a_programas_de_tecnico_laboral_mujeres: registroTabla1.no_per_direc_progr_técnico_laboral_mujeres,
				DIRECCIONAMIENTOS_A_FORMACIoN_PARA_EL_TRABAJO_REALIZADOS_SISE_8_numero_de_personas_que_culminaron_programas_de_formacion_y_capacitacion_para_el_trabajo: registroTabla1.no_per_que_culmi_progr_formac_y_capaci_par_el_trabajo,
				_8_1_numero_de_personas_que_culminaron_programas_de_formacion_y_capacitacion_para_el_trabajo_hombres: registroTabla1.no_per_que_culmi_progr_formac_y_capaci_par_el_trabajo_hombres,
				_8_1_1_numero_de_personas_que_culminaron_programas_de_formacion_en_competencias_claves_y_transversales_hombres: registroTabla1.no_per_que_culmi_progr_formac_compete_claves_y_trans_hombres,
				_8_1_2_numero_de_personas_que_culminaron_programas_de_formacion_en_tecnologias_de_la_informacion_y_las_comunicaciones_tic_hombres: registroTabla1.no_per_que_culmi_progr_formac_tecno_info_y_comunica_tic_hombres,
				_8_1_3_numero_de_personas_que_culminaron_programas_de_alfabetizacion_o_bachillerato_hombres: registroTabla1.no_per_que_culmi_progr_alfabetizacion_o_bachillerato_hombres,
				_8_1_4_numero_de_personas_que_culminaron_programas_de_entrenamiento_o_reentrenamiento_tecnico_hombres: registroTabla1.no_per_que_culmi_progr_entrevnamiento_o_reentre_técnico_hombres,
				_8_1_5_numero_de_personas_que_culminaron_programas_de_tecnico_laboral_hombres: registroTabla1.no_per_que_culmi_progr_técnico_laboral_hombres,
				_8_2_numero_de_personas_que_culminaron_programas_de_formacion_y_capacitacion_para_el_trabajo_mujeres: registroTabla1.no_per_que_culmi_progr_formac_y_capaci_par_el_trabajo_mujeres,
				_8_2_1_numero_de_personas_que_culminaron_programas_de_formacion_en_competencias_claves_y_transversales_mujeres: registroTabla1.no_per_que_culmi_progr_formac_compete_claves_y_trans_mujeres,
				_8_2_2_numero_de_personas_que_culminaron_programas_de_formacion_en_tecnologias_de_la_informacion_y_las_comunicaciones_tic_mujeres: registroTabla1.no_per_que_culmi_progr_formac_tecno_info_y_comunica_tic_mujeres,
				_8_2_3_numero_de_personas_que_culminaron_programas_de_alfabetizacion_o_bachillerato_mujeres: registroTabla1.no_per_que_culmi_progr_alfabetizacion_o_bachillerato_mujeres,
				_8_2_4_numero_de_personas_que_culminaron_programas_de_entrenamiento_o_reentrenamiento_tecnico_mujeres: registroTabla1.no_per_que_culmi_progr_entrevnamiento_o_reentre_técnico_mujeres,
				_8_2_5_numero_de_personas_que_culminaron_programas_de_tecnico_laboral_mujeres: registroTabla1.no_per_que_culmi_progr_técnico_laboral_mujeres,
				DIRECCIONAMIENTOS_A_EMPRENDIMIENTO_SISE_9_numero_de_personas_direccionadas_a_programas_de_emprendimiento: registroTabla1.tot_per_direc_progr_emprendimiento,
				_9_1_numero_de_personas_direccionadas_a_programas_de_emprendimiento_hombres: registroTabla1.tot_per_direc_progr_emprendimiento_hombres,
				_9_2_numero_de_personas_direccionadas_a_programas_de_emprendimiento_mujeres: registroTabla1.tot_per_direc_progr_emprendimiento_mujeres,
				_10_numero_de_pqrs_radicados_en_el_punto_de_atencion: registroTabla1.tot_PQRS_radicados,
				VACANTES_REGISTRADAS_TOTAL_SISE_Datos_hasta_abril_de_2017_por_CV_: null,
				PUESTOS_DE_TRABAJO_SISE_Datos_hasta_abril_de_2017_por_CV_: null,
				PUESTOS_DE_TRABAJO_CON_GESTIoN_SISE_Datos_desde_junio_de_2017_: null,
				PUESTOS_DE_TRABAJO_SIN_GESTIoN_SISE_Datos_desde_junio_de_2017_: null,
				TIPO_CAJA: null,
				TIPO_PUNTO_ATEN: tablaBase.tipo_de_punto_de_atencion || null,
				TERCERO_DE_UN_ENTE: null,
			};
			registrosFinales.push(registroFinal);
		}
	}


    // Iterar sobre los registros de la tabla 2
    for (const idPuntoAtencion of Object.keys(tabla2)) {
		const registrosTabla2 = tabla2[idPuntoAtencion];

		const tablaBase = tabla4[idPuntoAtencion] || {};

		for (const registroTabla2 of registrosTabla2) {
			const registroFinal = {
				ID_PUNTO_AT: registroTabla2.ID_PUNTO_ATENCIÓN,
				ID_PRESTAD: tablaBase.id_prestador_cipres || null,
				AÑO: registroTabla2.AÑO,
				MES: registroTabla2.MES,
				Marcacion_Sistema: registroTabla2.fuente,
				ID_PRESTADOR: tablaBase.id_prestador_cipres || null,
				Divipola_Departamento: tablaBase.divipola_asociada_a_la_url || null,
				Divipola_Municipio: tablaBase.divipola || null,
				TIPO_PRESTADOR: tablaBase.tipo_de_prestador || null,
				PRESTADOR: tablaBase.prestador || null,
				DEPARTAMENTO: tablaBase.departamento || null,
				MUNICIPIO: tablaBase.municipio || null,
				CONCACTENAR: tablaBase.departamento || null + tablaBase.municipio || null,
				CIUDAD_CAPITAL: null,
				DIRECCION: registroTabla2.DIRECCION,
				TIPO_PUNTO_DE_ATENCIoN: tablaBase.tipo_de_punto_de_atencion || null,

				TOTAL_INSCRITOS_NETO_SISE_1_numero_de_personas_inscritas_registradas_CV: registroTabla2.PERSONAS_INSCRITAS_NETO,
				TOTAL_INSCRITOS_NETO_HOMBRES_SISE_1_numero_de_personas_inscritas_registradas_CV: registroTabla2.PERSONAS_INSCRITAS_TOTAL_SALIDAS_Hombre,
				TOTAL_INSCRITOS_NETO_MUJERES_SISE_1_numero_de_personas_inscritas_registradas_CV: registroTabla2.PERSONAS_INSCRITAS_TOTAL_SALIDAS_Mujer,
				TOTAL_INSCRITOS_ENTRADAS_SISE_1_numero_de_personas_inscritas_registradas_CV: registroTabla2.PERSONAS_INSCRITAS_TOTAL_ENTRADAS,
				TOTAL_INSCRITOS_HOMBRES_ENTRADAS_SISE_1_1_numero_de_personas_inscritas_registradas_hombres_CV: registroTabla2.PERSONAS_INSCRITAS_HOMBRES,
				TOTAL_INSCRITOS_MUJERES_ENTRADAS_SISE_1_2_numero_de_personas_inscritas_registradas_mujeres_CV: registroTabla2.PERSONAS_INSCRITAS_MUJERES,
				TOTAL_INSCRITOS_SALIDAS_SISE: registroTabla2.PERSONAS_INSCRITAS_TOTAL_SALIDAS,
				TOTAL_INSCRITOS_JoVENES_SISE: registroTabla2.PERSONAS_INSCRITAS_TOTAL_SALIDAS_de_18_a_28_años,
				TOTAL_INSCRITOS_JoVENES_MUJERES_SISE: registroTabla2.PERSONAS_INSCRITAS_TOTAL_SALIDAS_de_18_a_28_años_mujeres,
				TOTAL_INSCRITOS_JoVENES_HOMBRES_SISE: registroTabla2.PERSONAS_INSCRITAS_TOTAL_SALIDAS_de_18_a_28_años_hombres,
				TOTAL_INSCRITOS_PcD_SISE: registroTabla2.PERSONAS_INSCRITAS_TOTAL_SALIDAS_discapacidad,
				TOTAL_INSCRITOS_PcD_MUJERES_SISE: registroTabla2.PERSONAS_INSCRITAS_TOTAL_SALIDAS_discapacidad_mujeres,
				TOTAL_INSCRITOS_PcD_HOMBRES_SISE: registroTabla2.PERSONAS_INSCRITAS_TOTAL_SALIDAS_discapacidad_hombre,
				TOTAL_INSCRITOS_VICTIMAS_SISE: registroTabla2.PERSONAS_INSCRITAS_TOTAL_SALIDAS_Victimas,
				TOTAL_INSCRITOS_VICTIMAS_MUJERES_SISE: registroTabla2.PERSONAS_INSCRITAS_TOTAL_SALIDAS_Victimas_mujeres,
				TOTAL_INSCRITOS_VICTIMAS_HOMBRES_SISE: registroTabla2.PERSONAS_INSCRITAS_TOTAL_SALIDAS_Victimas_hombres,
				Total_Oferentes_Neto_Migrantes_Venezolanos: registroTabla2.Total_Oferentes_Neto_Migrantes_Venezolanos,
				Total_Oferentes_Neto_Migrantes_Venezolanos_Mujeres: registroTabla2.Total_Oferentes_Neto_Migrantes_Venezolanos_Mujeres,
				Total_Oferentes_Neto_Migrantes_Venezolanos_Hombres: registroTabla2.Total_Oferentes_Neto_Migrantes_Venezolanos_Hombres,
				TOTAL_OFERENTES_ETNICOS: null,
				TOTAL_OFERENTES_ETNICOS_MUJERES: null,
				TOTAL_OFERENTES_ETNICOS_HOMBRES: null,
				REMISIONES_A_EMPLEADORES_TOTAL_SISE_2_numero_de_hojas_de_vida_remitidas_a_empleadores_CV: null,
				REMISIONES_A_EMPLEADORES_HOMBRES_SISE_2_1_numero_de_hojas_de_vida_remitidas_a_empleadores_hombres_CV: null,
				REMISIONES_A_EMPLEADORES_MUJERES_SISE_2_2_numero_de_hojas_de_vida_remitidas_a_empleadores_mujeres_CV: null,
				AUTOPOSTULADOS_SISE: registroTabla2.OFERENTES_AUTOPOSTULADOS,
				OFERENTES_AUTOPOSTULADOS_HOMBRES: registroTabla2.OFERENTES_AUTOPOSTULADOS_HOMBRES,
				OFERENTES_AUTOPOSTULADOS_MUJERES: registroTabla2.OFERENTES_AUTOPOSTULADOS_MUJERES,
				OFERENTES_JoVENES_AUTOPOSTULADOS: registroTabla2.OFERENTES_AUTOPOSTULADOS_DE_18_A_28_AÑOS,
				OFERENTES_JoVENES_AUTOPOSTULADOS_MUJERES: registroTabla2.OFERENTES_AUTOPOSTULADOS_DE_18_A_28_AÑOS_MUJERES,
				OFERENTES_JoVENES_AUTOPOSTULADOS_HOMBRES: registroTabla2.OFERENTES_AUTOPOSTULADOS_DE_18_A_28_AÑOS_HOMBRES,
				OFERENTES_PcD_AUTOPOSTULADOS: registroTabla2.OFERENTES_AUTOPOSTULADOS_DISCAPACIDAD,
				OFERENTES_PcD_AUTOPOSTULADOS_MUJERES: registroTabla2.OFERENTES_AUTOPOSTULADOS_DISCAPACIDAD_MUJERES,
				OFERENTES_PcD_AUTOPOSTULADOS_HOMBRES: registroTabla2.OFERENTES_AUTOPOSTULADOS_DISCAPACIDAD_HOMBRES,
				OFERENTES_VICTIMAS_AUTOPOSTULADOS: registroTabla2.OFERENTES_AUTOPOSTULADOS_VICTIMAS,
				OFERENTES_VICTIMAS_AUTOPOSTULADOS_MUJERES: registroTabla2.OFERENTES_AUTOPOSTULADOS_VICTIMAS_MUJERES,
				OFERENTES_VICTIMAS_AUTOPOSTULADOS_HOMBRES: registroTabla2.OFERENTES_AUTOPOSTULADOS_VICTIMAS_HOMBRES,
				OFERENTES_AUTOPOSTULADOS_MIGRANTES_VENEZOLANOS: registroTabla2.OFERENTES_AUTOPOSTULADOS_MIGRANTES_VENEZOLANOS,
				OFERENTES_AUTOPOSTULADOS_MIGRANTES_VENEZOLANOS_MUJERES: registroTabla2.OFERENTES_AUTOPOSTULADOS_MIGRANTES_VENEZOLANOS_MUJERES,
				OFERENTES_AUTOPOSTULADOS_MIGRANTES_VENEZOLANOS_HOMBRES: registroTabla2.OFERENTES_AUTOPOSTULADOS_MIGRANTES_VENEZOLANOS_HOMBRES,
				REMITIDOS_A_EMPLEADORES_SIN_AUTOPOSTULADOS_SISE_2_numero_de_hojas_de_vida_remitidas_a_empleadores_CV: null , // Preguntar
				REMITIDOS_A_EMPLEADORES_SIN_AUTOPOSTULADOS_HOMBRES_SISE_2_1_numero_de_hojas_de_vida_remitidas_a_empleadores_hombres_CV: null , // Preguntar
				_REMITIDOS_A_EMPLEADORES_SIN_AUTOPOSTULADOS_MUJERES_SISE_2_2_numero_de_hojas_de_vida_remitidas_a_empleadores_mujeres_CV: null , // Preguntar
				HOJAS_DE_VIDA_REMITIDAS_DIRECTAMENTE_POR_EL_PUNTO_DE_ATENCIoN: registroTabla2.REMISIONES_A_EMPLEADORES_TOTAL,
				HOJAS_DE_VIDA_REMITIDAS_DIRECTAMENTE_POR_EL_PUNTO_DE_ATENCIoN_HOMBRES: registroTabla2.REMISIONES_A_EMPLEADORES_HOMBRES, // Preguntar
				HOJAS_DE_VIDA_REMITIDAS_DIRECTAMENTE_POR_EL_PUNTO_DE_ATENCIoN_MUJERES: registroTabla2.REMISIONES_A_EMPLEADORES_MUJERES, // Preguntar
				REMITIDOS_POR_EL_PUNTO_DE_ATENCIoN_TOTAL_SISE: registroTabla2.OFERENTES_REMITIDOS_POR_EL_PUNTO_DE_ATENCION,
				REMITIDOS_POR_AUTOPOSTULACIoN_ASISTIDA_TOTAL_SISE_2_numero_de_hojas_de_vida_remitidas_a_empleadores_CV: registroTabla2.OFERENTES_REMITIDOS_POR_AUTOPOSTULACION_ASISTIDA,
				TOTAL_REMISIONES_A_EMPLEADORES_VICTIMAS: registroTabla2.REMISIONES_A_EMPLEADORES_VICTIMAS,
				TOTAL_REMISIONES_A_EMPLEADORES_VICTIMAS_MUJERES: registroTabla2.REMISIONES_A_EMPLEADORES_VICTIMAS_MUJERES,
				TOTAL_REMISIONES_A_EMPLEADORES_VICTIMAS_HOMBRES: registroTabla2.REMISIONES_A_EMPLEADORES_VICTIMAS_HOMBRES,
				REMISIONES_A_EMPLEADORES_VICTIMAS: registroTabla2.REMISIONES_A_EMPLEADORES_VICTIMAS,
				REMISIONES_A_EMPLEADORES_VICTIMAS_MUJERES: registroTabla2.REMISIONES_A_EMPLEADORES_VICTIMAS_MUJERES,
				REMISIONES_A_EMPLEADORES_VICTIMAS_HOMBRES: registroTabla2.REMISIONES_A_EMPLEADORES_VICTIMAS_HOMBRES,
				TOTAL_REMISIONES_A_EMPLEADORES_PCD: registroTabla2.REMISIONES_A_EMPLEADORES_PCD,
				TOTAL_REMISIONES_A_EMPLEADORES_PCD_MUJERES: registroTabla2.REMISIONES_A_EMPLEADORES_PCD_MUJERES,
				TOTAL_REMISIONES_A_EMPLEADORES_PCD_HOMBRES: registroTabla2.REMISIONES_A_EMPLEADORES_PCD_HOMBRES,
				REMISIONES_A_EMPLEADORES_PCD: registroTabla2.REMISIONES_A_EMPLEADORES_PCD,
				REMISIONES_A_EMPLEADORES_PCD_MUJERES: registroTabla2.REMISIONES_A_EMPLEADORES_PCD_MUJERES,
				REMISIONES_A_EMPLEADORES_PCD_HOMBRES: registroTabla2.REMISIONES_A_EMPLEADORES_PCD_HOMBRES,
				TOTAL_REMISIONES_A_EMPLEADORES_DE_18_A_28_AÑOS: registroTabla2.REMISIONES_A_EMPLEADORES_DE_18_A_28_AÑOS,
				TOTAL_REMISIONES_A_EMPLEADORES_DE_18_A_28_AÑOS_MUJERES: registroTabla2.REMISIONES_A_EMPLEADORES_DE_18_A_28_AÑOS_MUJERES,
				TOTAL_REMISIONES_A_EMPLEADORES_DE_18_A_28_AÑOS_HOMBRES: registroTabla2.REMISIONES_A_EMPLEADORES_DE_18_A_28_AÑOS_HOMBRES,
				REMISIONES_A_EMPLEADORES_DE_18_A_28_AÑOS: registroTabla2.REMISIONES_A_EMPLEADORES_DE_18_A_28_AÑOS,
				REMISIONES_A_EMPLEADORES_DE_18_A_28_AÑOS_MUJERES: registroTabla2.REMISIONES_A_EMPLEADORES_DE_18_A_28_AÑOS_MUJERES,
				REMISIONES_A_EMPLEADORES_DE_18_A_28_AÑOS_HOMBRES: registroTabla2.REMISIONES_A_EMPLEADORES_DE_18_A_28_AÑOS_HOMBRES,
				TOTAL_REMISIONES_A_EMPLEADORES_MIGRANTES_VENEZOLANOS: registroTabla2.REMISIONES_A_EMPLEADORES_MIGRANTES_VENEZOLANOS,
				TOTAL_REMISIONES_A_EMPLEADORES_MIGRANTES_VENEZOLANOS_MUJERES: registroTabla2.REMISIONES_A_EMPLEADORES_MIGRANTES_VENEZOLANOS_MUJERES,
				TOTAL_REMISIONES_A_EMPLEADORES_MIGRANTES_VENEZOLANOS_HOMBRES: registroTabla2.REMISIONES_A_EMPLEADORES_MIGRANTES_VENEZOLANOS_HOMBRES,
				REMISIONES_A_EMPLEADORES_MIGRANTES_VENEZOLANOS: registroTabla2.REMISIONES_A_EMPLEADORES_MIGRANTES_VENEZOLANOS,
				REMISIONES_A_EMPLEADORES_MIGRANTES_VENEZOLANOS_MUJERES: registroTabla2.REMISIONES_A_EMPLEADORES_MIGRANTES_VENEZOLANOS_MUJERES,
				REMISIONES_A_EMPLEADORES_MIGRANTES_VENEZOLANOS_HOMBRES: registroTabla2.REMISIONES_A_EMPLEADORES_MIGRANTES_VENEZOLANOS_HOMBRES,
				REMISIONES_A_EMPLEADORES_ETNICOS: null,
				REMISIONES_A_EMPLEADORES_ETNICOS_MUJERES: null,
				REMISIONES_A_EMPLEADORES_ETNICOS_HOMBRES: null,
				TOTAL_COLOCADOS_SISE_3_numero_de_personas_colocadas_CV: registroTabla2.TOTAL_COLOCADOS,
				COLOCADOS_ENTRADAS_SISE_3_numero_de_personas_colocadas_CV: registroTabla2.COLOCADOS_ACTUALES,
				COLOCADOS_DEVUELTOS_SISE: registroTabla2.COLOCADOS_DEVUELTOS,
				COLOCADOS_HOMBRES_SISE_3_1_numero_de_personas_colocadas_hombres_CV: registroTabla2.COLOCADOS_HOMBRES,
				COLOCADOS_MUJERES_SISE_3_2_numero_de_personas_colocadas_mujeres_CV: registroTabla2.COLOCADOS_MUJERES,
				COLOCADOS_DIRECTOS_SISE_3_numero_de_personas_colocadas_CV: registroTabla2.COLOCADOS_DIRECTOS,
				COLOCADOS_DIRECTOS_HOMBRES_SISE_3_1_numero_de_personas_colocadas_hombres_CV: registroTabla2.Total_Colocados_Directos_Hombres,
				COLOCADOS_DIRECTOS_MUJERES_SISE_3_2_numero_de_personas_colocadas_mujeres_CV: registroTabla2.Total_Colocados_Directos_Mujeres,
				COLOCADOS_INDIRECTOS_SISE: registroTabla2.COLOCADOS_INDIRECTOS,
				COLOCADOS_INDIRECTOS_HOMBRES_SISE: registroTabla2.Total_Colocados_Indirectos_Hombres,
				COLOCADOS_INDIRECTOS_MUJERES_SISE: registroTabla2.Total_Colocados_Indirectos_Mujeres,
				COLOCADOS_DIRECTOS_VICTIMAS_SISE: registroTabla2.TOTAL_COLOCADOS_DIRECTOS_VICTIMAS,
				COLOCADOS_DIRECTOS_VICTIMAS_MUJERES_SISE: registroTabla2.TOTAL_COLOCADOS_DIRECTOS_VICTIMAS_MUJERES,
				COLOCADOS_DIRECTOS_VICTIMAS_HOMBRES_SISE: registroTabla2.TOTAL_COLOCADOS_DIRECTOS_VICTIMAS_HOMBRE,
				COLOCADOS_DIRECTOS_PcD_SISE: registroTabla2.TOTAL_COLOCADOS_DIRECTOS_PCD,
				COLOCADOS_DIRECTOS_PcD_MUJERES_SISE: registroTabla2.TOTAL_COLOCADOS_DIRECTOS_PCD_MUJERES,
				COLOCADOS_DIRECTOS_PcD_HOMBRES_SISE: registroTabla2.TOTAL_COLOCADOS_DIRECTOS_PCD_HOMBRE,
				COLOCADOS_DIRECTOS_18_A_28_AÑOS_SISE: registroTabla2.TOTAL_COLOCADOS_DIRECTOS_DE_18_A_28_AÑOS,
				COLOCADOS_DIRECTOS_18_A_28_AÑOS_MUJERES_SISE: registroTabla2.TOTAL_COLOCADOS_DIRECTOS_DE_18_A_28_AÑOS_MUJERES,
				COLOCADOS_DIRECTOS_18_A_28_AÑOS_HOMBRES_SISE: registroTabla2.TOTAL_COLOCADOS_DIRECTOS_DE_18_A_28_AÑOS_HOMBRE,
				COLOCADOS_DIRECTOS_MIGRANTES_VENEZOLANOS: registroTabla2.TOTAL_COLOCADOS_DIRECTOS_MIGRANTES_VENEZOLANOS,
				COLOCADOS_DIRECTOS_MIGRANTES_VENEZOLANOS_MUJERES: registroTabla2.TOTAL_COLOCADOS_DIRECTOS_MIGRANTES_VENEZOLANOS_MUJERES,
				COLOCADOS_DIRECTOS_MIGRANTES_VENEZOLANOS_HOMBRE: registroTabla2.TOTAL_COLOCADOS_DIRECTOS_MIGRANTES_VENEZOLANOS_HOMBRE,
				COLOCADOS_DIRECTOS_ETNICOS: null,
				COLOCADOS_DIRECTOS_ETNICOS_MUJERES: null,
				COLOCADOS_DIRECTOS_ETNICOS_HOMBRES: null,
				SEDES_INSCRITAS_TOTAL_NETO_SISE_4_numero_de_empleadores_registrados_inscritos_CV: registroTabla2.EMPRESAS_SEDES_INSCRITAS_NETO,
				SEDES_INSCRITAS_ENTRADAS_SISE_4_numero_de_empleadores_registrados_inscritos_CV: registroTabla2.EMPRESAS_SEDES_TOTAL_ENTRADAS,
				SEDES_INSCRITAS_SALIDAS_SISE: registroTabla2.EMPRESAS_SEDES_TOTAL_SALIDAS,
				EMPRESAS_INSCRITAS_SISE_4_numero_de_empleadores_registrados_inscritos_CV: registroTabla2.EMPRESAS_INSCRITAS,
				DIRECCIONAMIENTOS_INDIVIDUALES_DE_ORIENTACIoN_LABORAL_REALIZADOS_SISE_5_numero_de_personas_atendidas_en_entrevistas_de_orientacion_ocupacional_CV: registroTabla2.Orientación_Laboral_Entrevistas,
				DIRECCIONAMIENTOS_INDIVIDUALES_DE_ORIENTACIoN_LABORAL_REALIZADOS_HOMBRES_SISE_5_1_numero_de_personas_atendidas_en_entrevistas_de_orientacion_ocupacional_hombres_CV: registroTabla2.Orientación_Laboral_Entrevistas_Hombres,
				DIRECCIONAMIENTOS_INDIVIDUALES_DE_ORIENTACIoN_LABORAL_REALIZADOS_MUJERES_SISE_5_2_numero_de_personas_atendidas_en_entrevistas_de_orientacion_ocupacional_mujeres_CV: registroTabla2.Orientación_Laboral_Entrevistas_Mujeres,
				VICTIMAS_DIRECCIONAMIENTOS_INDIVIDUALES_DE_ORIENTACIoN_LABORAL_SISE: registroTabla2.Orientación_Laboral_Entrevistas_victimas,
				VICTIMAS_DIRECCIONAMIENTOS_INDIVIDUALES_DE_ORIENTACIoN_LABORAL_Mujeres_SISE: registroTabla2.Orientación_Laboral_Entrevistas_victimas_mujeres,
				VICTIMAS_DIRECCIONAMIENTOS_INDIVIDUALES_DE_ORIENTACIoN_LABORAL_Hombres_SISE: registroTabla2.Orientación_Laboral_Entrevistas_victimas_hombres,
				PCD_DIRECCIONAMIENTOS_INDIVIDUALES_DE_ORIENTACIoN_LABORAL_SISE: registroTabla2.Orientación_Laboral_Entrevistas_PcD,
				PCD_DIRECCIONAMIENTOS_INDIVIDUALES_DE_ORIENTACIoN_LABORAL_Mujeres_SISE: registroTabla2.Orientación_Laboral_Entrevistas_PcD_mujeres,
				PCD_DIRECCIONAMIENTOS_INDIVIDUALES_DE_ORIENTACIoN_LABORAL_Hombres_SISE: registroTabla2.Orientación_Laboral_Entrevistas_PcD_hombres,
				_18_a_28_AÑOS_DIRECCIONAMIENTOS_INDIVIDUALES_DE_ORIENTACIoN_LABORAL_SISE: registroTabla2.Orientación_Laboral_Entrevistas_de_18_a_28_años,
				_18_a_28_AÑOS_DIRECCIONAMIENTOS_INDIVIDUALES_DE_ORIENTACIoN_LABORAL_Mujeres_SISE: registroTabla2.Orientación_Laboral_Entrevistas_18_a_28_mujeres,
				_18_a_28_AÑOS_DIRECCIONAMIENTOS_INDIVIDUALES_DE_ORIENTACIoN_LABORAL_Hombres_SISE: registroTabla2.Orientación_Laboral_Entrevistas_18_a_28_hombres,
				MIGRANTES_VENEZOLANOS_DIRECCIONAMIENTOS_INDIVIDUALES_DE_ORIENTACIoN_LABORAL_SISE: registroTabla2.Orientación_Laboral_Entrevistas_Migrantes_Venezolanos,
				MIGRANTES_VENEZOLANOS_DIRECCIONAMIENTOS_INDIVIDUALES_DE_ORIENTACIoN_LABORAL_Mujeres_SISE: registroTabla2.Orientación_Laboral_Entrevistas_Migrantes_Venezolanos_Mujeres,
				MIGRANTES_VENEZOLANOS_DIRECCIONAMIENTOS_INDIVIDUALES_DE_ORIENTACIoN_LABORAL_Hombres_SISE: registroTabla2.Orientación_Laboral_Entrevistas_Migrantes_Venezolanos_Hombres,
				ETNICOS_DIRECCIONAMIENTOS_INDIVIDUALES_DE_ORIENTACIoN_LABORAL_SISE: null,
				ETNICOS_MUJERES_DIRECCIONAMIENTOS_INDIVIDUALES_DE_ORIENTACIoN_LABORAL_SISE: null,
				ETNICOS_HOMBRES_DIRECCIONAMIENTOS_INDIVIDUALES_DE_ORIENTACIoN_LABORAL_SISE: null,
				DIRECCIONAMIENTOS_GRUPALES_DE_ORIENTACIoN_LABORAL_REALIZADOS_SISE_6_numero_de_personas_atendidas_en_actividades_grupales_de_orientacion_ocupacional: registroTabla2.Orientación_Laboral_Actividades_Grupales,
				DIRECCIONAMIENTOS_GRUPALES_DE_ORIENTACIoN_LABORAL_REALIZADOS_HOMBRES_SISE_6_1_numero_de_personas_atendidas_en_actividades_grupales_de_orientacion_ocupacional_hombres: registroTabla2.Orientación_Laboral_Actividades_Grupales_Hombres,
				DIRECCIONAMIENTOS_GRUPALES_DE_ORIENTACIoN_LABORAL_REALIZADOS_MUJERES_SISE_6_2_numero_de_personas_atendidas_en_actividades_grupales_de_orientacion_ocupacional_mujeres: registroTabla2.Orientación_Laboral_Actividades_Grupales_Mujeres,
				DIRECCIONAMIENTOS_GRUPALES_DE_ORIENTACIoN_LABORAL_REALIZADOS_A_PERSONAS_18_a_28_AÑOS: registroTabla2.Orientación_Laboral_Actividades_Grupales_18_a_28_años,
				DIRECCIONAMIENTOS_GRUPALES_DE_ORIENTACIoN_LABORAL_REALIZADOS_A_PERSONAS_18_a_28_AÑOS_MUJERES: registroTabla2.Orientación_Laboral_Actividades_Grupales_18_a_28_años_Mujeres,
				DIRECCIONAMIENTOS_GRUPALES_DE_ORIENTACIoN_LABORAL_REALIZADOS_A_PERSONAS_18_a_28_AÑOS_HOMBRES: registroTabla2.Orientación_Laboral_Actividades_Grupales_18_a_28_años_Hombres,
				DIRECCIONAMIENTOS_GRUPALES_DE_ORIENTACIoN_LABORAL_REALIZADOS_A_PcD: registroTabla2.Orientación_Laboral_Actividades_Grupales_Discapacidad,
				DIRECCIONAMIENTOS_GRUPALES_DE_ORIENTACIoN_LABORAL_REALIZADOS_A_PcD_MUJERES: registroTabla2.Orientación_Laboral_Actividades_Grupales_Discapacidad_Hombres,
				DIRECCIONAMIENTOS_GRUPALES_DE_ORIENTACIoN_LABORAL_REALIZADOS_A_PcD_HOMBRES: registroTabla2.Orientación_Laboral_Actividades_Grupales_Discapacidad_Mujeres,
				DIRECCIONAMIENTOS_GRUPALES_DE_ORIENTACIoN_LABORAL_REALIZADOS_A_VICTIMAS: registroTabla2.Orientación_Laboral_Actividades_Grupales_Victimas,
				DIRECCIONAMIENTOS_GRUPALES_DE_ORIENTACIoN_LABORAL_REALIZADOS_A_VICTIMAS_MUJERES: registroTabla2.Orientación_Laboral_Actividades_Grupales_Victimas_Mujeres,
				DIRECCIONAMIENTOS_GRUPALES_DE_ORIENTACIoN_LABORAL_REALIZADOS_A_VICTIMAS_HOMBRES: registroTabla2.Orientación_Laboral_Actividades_Grupales_Víctimas_Hombres,
				DIRECCIONAMIENTOS_GRUPALES_DE_ORIENTACIoN_LABORAL_REALIZADOS_A_Migrantes_Venezolanos: registroTabla2.Orientación_Laboral_Entrevistas_Migrantes_Venezolanos,
				DIRECCIONAMIENTOS_GRUPALES_DE_ORIENTACIoN_LABORAL_REALIZADOS_A_Migrantes_Venezolanos_MUJERES: registroTabla2.Orientación_Laboral_Entrevistas_Migrantes_Venezolanos_Hombres,
				DIRECCIONAMIENTOS_GRUPALES_DE_ORIENTACIoN_LABORAL_REALIZADOS_A_Migrantes_Venezolanos_HOMBRES: registroTabla2.Orientación_Laboral_Entrevistas_Migrantes_Venezolanos_Mujeres,
				DIRECCIONAMIENTOS_GRUPALES_DE_ORIENTACIoN_LABORAL_REALIZADOS_A_ETNICOS: null,
				DIRECCIONAMIENTOS_GRUPALES_DE_ORIENTACIoN_LABORAL_REALIZADOS_A_ETNICOS_MUJERES: null,
				DIRECCIONAMIENTOS_GRUPALES_DE_ORIENTACIoN_LABORAL_REALIZADOS_A_ETNICOS_HOMBRES: null,
				DIRECCIONAMIENTOS_A_FORMACIoN_PARA_EL_TRABAJO_SISE_7_numero_de_personas_direccionadas_a_programas_de_formacion_y_capacitacion_para_el_trabajo: registroTabla2.Capacitación_Registrados,
				_7_1_numero_de_personas_direccionadas_a_programas_de_formacion_y_capacitacion_para_el_trabajo_hombres: registroTabla2.Capacitación_Registrados_Hombres,
				_7_1_1_numero_de_personas_direccionadas_a_programas_de_formacion_en_competencias_claves_y_transversales_hombres: registroTabla2.Capacitación_Registrados_Competen_claves_trasversales_Hombres,
				_7_1_2_numero_de_personas_direccionadas_a_programas_de_formacion_en_tecnologias_de_la_informacion_y_las_comunicaciones_tic_hombres: registroTabla2.Capacitación_Registrados_TICS_Hombres,
				_7_1_3_numero_de_personas_direccionadas_a_programas_de_alfabetizacion_o_bachillerato_hombres: registroTabla2.Capacitación_Registrados_alfabetización_bachillerato_Hombres,
				_7_1_4_numero_de_personas_direccionadas_a_programas_de_entrenamiento_o_reentrenamiento_tecnico_hombres: registroTabla2.Capacitación_Registrados_Curso_Seminario_Diplomado_Hombres,
				_7_1_5_numero_de_personas_direccionadas_a_programas_de_tecnico_laboral_hombres: registroTabla2.Capacitación_Registrados_Técnico_Laboral_Hombres,
				_7_2_numero_de_personas_direccionadas_a_programas_de_formacion_y_capacitacion_para_el_trabajo_mujeres: registroTabla2.Capacitación_Registrados_Mujeres,
				_7_2_1_numero_de_personas_direccionadas_a_programas_de_formacion_en_competencias_claves_y_transversales_mujeres: registroTabla2.Capacitación_Registrados_Competen_claves_trasversales_Mujeres,
				_7_2_2_numero_de_personas_direccionadas_a_programas_de_formacion_en_tecnologias_de_la_informacion_y_las_comunicaciones_tic_mujeres: registroTabla2.Capacitación_Registrados_TICS_Mujeres,
				_7_2_3_numero_de_personas_direccionadas_a_programas_de_alfabetizacion_o_bachillerato_mujeres: registroTabla2.Capacitación_Registrados_alfabetización_bachillerato_Mujeres,
				_7_2_4_numero_de_personas_direccionadas_a_programas_de_entrenamiento_o_reentrenamiento_tecnico_mujeres: registroTabla2.Capacitación_Registrados_Curso_Seminario_Diplomado_Mujeres,
				_7_2_5_numero_de_personas_direccionadas_a_programas_de_tecnico_laboral_mujeres: registroTabla2.Capacitación_Registrados_Técnico_Laboral_Mujeres,
				DIRECCIONAMIENTOS_A_FORMACIoN_PARA_EL_TRABAJO_REALIZADOS_SISE_8_numero_de_personas_que_culminaron_programas_de_formacion_y_capacitacion_para_el_trabajo: registroTabla2.Capacitación_Finalizados,
				_8_1_numero_de_personas_que_culminaron_programas_de_formacion_y_capacitacion_para_el_trabajo_hombres: registroTabla2.Capacitación_Finalizados_Hombres,
				_8_1_1_numero_de_personas_que_culminaron_programas_de_formacion_en_competencias_claves_y_transversales_hombres: registroTabla2.Capacitación_Finalizados_Competen_claves_trasversales_Hombres,
				_8_1_2_numero_de_personas_que_culminaron_programas_de_formacion_en_tecnologias_de_la_informacion_y_las_comunicaciones_tic_hombres: registroTabla2.Capacitación_Finalizados_TICS_Hombres,
				_8_1_3_numero_de_personas_que_culminaron_programas_de_alfabetizacion_o_bachillerato_hombres: registroTabla2.Capacitación_Finalizados_alfabetización_bachillerato_Hombres,
				_8_1_4_numero_de_personas_que_culminaron_programas_de_entrenamiento_o_reentrenamiento_tecnico_hombres: registroTabla2.Capacitación_Finalizados_Curso_Seminario_Diplomado_Hombres,
				_8_1_5_numero_de_personas_que_culminaron_programas_de_tecnico_laboral_hombres: registroTabla2.Capacitación_Finalizados_Técnico_Laboral_Hombres,
				_8_2_numero_de_personas_que_culminaron_programas_de_formacion_y_capacitacion_para_el_trabajo_mujeres: registroTabla2.Capacitación_Finalizados_Mujeres,
				_8_2_1_numero_de_personas_que_culminaron_programas_de_formacion_en_competencias_claves_y_transversales_mujeres: registroTabla2.Capacitación_Finalizados_Competen_claves_trasversales_Mujeres,
				_8_2_2_numero_de_personas_que_culminaron_programas_de_formacion_en_tecnologias_de_la_informacion_y_las_comunicaciones_tic_mujeres: registroTabla2.Capacitación_Finalizados_TICS_Mujeres,
				_8_2_3_numero_de_personas_que_culminaron_programas_de_alfabetizacion_o_bachillerato_mujeres: registroTabla2.Capacitación_Finalizados_alfabetización_bachillerato_Mujeres,
				_8_2_4_numero_de_personas_que_culminaron_programas_de_entrenamiento_o_reentrenamiento_tecnico_mujeres: registroTabla2.Capacitación_Finalizados_Curso_Seminario_Diplomado_Mujeres,
				_8_2_5_numero_de_personas_que_culminaron_programas_de_tecnico_laboral_mujeres: registroTabla2.Capacitación_Finalizados_Técnico_Laboral_Mujeres,
				DIRECCIONAMIENTOS_A_EMPRENDIMIENTO_SISE_9_numero_de_personas_direccionadas_a_programas_de_emprendimiento: registroTabla2.Emprendimiento_Registrados,
				_9_1_numero_de_personas_direccionadas_a_programas_de_emprendimiento_hombres: registroTabla2.Emprendimiento_Registrados_Curso_Diplomado_Otro_Hombres,
				_9_2_numero_de_personas_direccionadas_a_programas_de_emprendimiento_mujeres: registroTabla2.Emprendimiento_Registrados_Curso_Diplomado_Otro_Mujeres,
				_10_numero_de_pqrs_radicados_en_el_punto_de_atencion: null,
				VACANTES_REGISTRADAS_TOTAL_SISE_Datos_hasta_abril_de_2017_por_CV_: registroTabla2.VACANTES_REGISTRADAS_TOTAL,
				PUESTOS_DE_TRABAJO_SISE_Datos_hasta_abril_de_2017_por_CV_: registroTabla2.PUESTOS_DE_TRABAJO,
				PUESTOS_DE_TRABAJO_CON_GESTIoN_SISE_Datos_desde_junio_de_2017_: registroTabla2.PUESTOS_DE_TRABAJO_CON_GESTION,
				PUESTOS_DE_TRABAJO_SIN_GESTIoN_SISE_Datos_desde_junio_de_2017_: registroTabla2.PUESTOS_DE_TRABAJO_SIN_GESTION,
				TIPO_CAJA: null, // Preguntar
				TIPO_PUNTO_ATEN: tablaBase.tipo_de_punto_de_atencion || null,
				TERCERO_DE_UN_ENTE: null,
			};

			registrosFinales.push(registroFinal);
		}
    }

	for (const id of Object.keys(tabla3)) {
		const registrosTabla3 = tabla3[id];

		const tablaBase = tabla4[id] || {};

		for (const registroTabla3 of registrosTabla3) {
			const registroFinal = {
				ID_PUNTO_AT: registroTabla3.ID_PUNTO_AT,
				ID_PRESTAD: tablaBase.id_prestador_cipres || null,
				AÑO: registroTabla3.AÑO,
				MES: registroTabla3.MES,
				Marcacion_Sistema: registroTabla3.fuente,
				ID_PRESTADOR: tablaBase.id_prestador_cipres || null,
				Divipola_Departamento: tablaBase.divipola_asociada_a_la_url || null,
				Divipola_Municipio: tablaBase.divipola || null,
				TIPO_PRESTADOR: tablaBase.tipo_de_prestador || null,
				PRESTADOR: tablaBase.prestador || null,
				DEPARTAMENTO: tablaBase.departamento || null,
				MUNICIPIO: tablaBase.municipio || null,
				CONCACTENAR: tablaBase.departamento || null + tablaBase.municipio || null,
				CIUDAD_CAPITAL: null,
				DIRECCION: null,
				TIPO_PUNTO_DE_ATENCIoN: tablaBase.tipo_de_punto_de_atencion || null,

				TOTAL_INSCRITOS_NETO_SISE_1_numero_de_personas_inscritas_registradas_CV: registroTabla3.INSCRITOS_HOMBRE + registroTabla3.INSCRITOS_MUJER,
				TOTAL_INSCRITOS_NETO_HOMBRES_SISE_1_numero_de_personas_inscritas_registradas_CV: registroTabla3.INSCRITOS_HOMBRE,
				TOTAL_INSCRITOS_NETO_MUJERES_SISE_1_numero_de_personas_inscritas_registradas_CV: registroTabla3.INSCRITOS_MUJER,
				TOTAL_INSCRITOS_ENTRADAS_SISE_1_numero_de_personas_inscritas_registradas_CV: registroTabla3.INSCRITOS_HOMBRE + registroTabla3.INSCRITOS_MUJER,
				TOTAL_INSCRITOS_HOMBRES_ENTRADAS_SISE_1_1_numero_de_personas_inscritas_registradas_hombres_CV: registroTabla3.INSCRITOS_HOMBRE,
				TOTAL_INSCRITOS_MUJERES_ENTRADAS_SISE_1_2_numero_de_personas_inscritas_registradas_mujeres_CV: registroTabla3.INSCRITOS_MUJER,
				TOTAL_INSCRITOS_SALIDAS_SISE: null,
				TOTAL_INSCRITOS_JoVENES_SISE: registroTabla3.INSCRITOS_JOVENES_MUJER + registroTabla3.INSCRITOS_JOVENES_HOMBRE,
				TOTAL_INSCRITOS_JoVENES_MUJERES_SISE: registroTabla3.INSCRITOS_JOVENES_MUJER,
				TOTAL_INSCRITOS_JoVENES_HOMBRES_SISE: registroTabla3.INSCRITOS_JOVENES_HOMBRE,
				TOTAL_INSCRITOS_PcD_SISE: registroTabla3.INSCRITOS_PCD_MUJER + registroTabla3.INSCRITOS_PCD_HOMBRE,
				TOTAL_INSCRITOS_PcD_MUJERES_SISE: registroTabla3.INSCRITOS_PCD_MUJER,
				TOTAL_INSCRITOS_PcD_HOMBRES_SISE: registroTabla3.INSCRITOS_PCD_HOMBRE,
				TOTAL_INSCRITOS_VICTIMAS_SISE: registroTabla3.INSCRITOS_RUV_MUJER + registroTabla3.INSCRITOS_RUV_HOMBRE,
				TOTAL_INSCRITOS_VICTIMAS_MUJERES_SISE: registroTabla3.INSCRITOS_RUV_MUJER,
				TOTAL_INSCRITOS_VICTIMAS_HOMBRES_SISE: registroTabla3.INSCRITOS_RUV_HOMBRE,
				Total_Oferentes_Neto_Migrantes_Venezolanos: null,
				Total_Oferentes_Neto_Migrantes_Venezolanos_Mujeres: null,
				Total_Oferentes_Neto_Migrantes_Venezolanos_Hombres: null,
				TOTAL_OFERENTES_ETNICOS: null,
				TOTAL_OFERENTES_ETNICOS_MUJERES: null,
				TOTAL_OFERENTES_ETNICOS_HOMBRES: null,
				REMISIONES_A_EMPLEADORES_TOTAL_SISE_2_numero_de_hojas_de_vida_remitidas_a_empleadores_CV: null,
				REMISIONES_A_EMPLEADORES_HOMBRES_SISE_2_1_numero_de_hojas_de_vida_remitidas_a_empleadores_hombres_CV: null,
				REMISIONES_A_EMPLEADORES_MUJERES_SISE_2_2_numero_de_hojas_de_vida_remitidas_a_empleadores_mujeres_CV: null,
				AUTOPOSTULADOS_SISE: registroTabla3.POSTULACIONES_HOMBRE_AUTO + registroTabla3.POSTULACIONES_MUJER_AUTO,
				OFERENTES_AUTOPOSTULADOS_HOMBRES: registroTabla3.POSTULACIONES_HOMBRE_AUTO,
				OFERENTES_AUTOPOSTULADOS_MUJERES: registroTabla3.POSTULACIONES_MUJER_AUTO,
				OFERENTES_JoVENES_AUTOPOSTULADOS: registroTabla3.POSTS_JOVENES_MUJER_AUTO + registroTabla3.POSTS_JOVENES_HOMBRE_AUTO,
				OFERENTES_JoVENES_AUTOPOSTULADOS_MUJERES: registroTabla3.POSTS_JOVENES_MUJER_AUTO,
				OFERENTES_JoVENES_AUTOPOSTULADOS_HOMBRES: registroTabla3.POSTS_JOVENES_HOMBRE_AUTO,
				OFERENTES_PcD_AUTOPOSTULADOS: registroTabla3.POSTS_PCD_MUJER_AUTO + registroTabla3.POSTS_PCD_HOMBRE_AUTO,
				OFERENTES_PcD_AUTOPOSTULADOS_MUJERES: registroTabla3.POSTS_PCD_MUJER_AUTO,
				OFERENTES_PcD_AUTOPOSTULADOS_HOMBRES: registroTabla3.POSTS_PCD_HOMBRE_AUTO,
				OFERENTES_VICTIMAS_AUTOPOSTULADOS: registroTabla3.POSTS_RUV_MUJER_AUTO + registroTabla3.POSTS_RUV_HOMBRE_AUTO,
				OFERENTES_VICTIMAS_AUTOPOSTULADOS_MUJERES: registroTabla3.POSTS_RUV_MUJER_AUTO,
				OFERENTES_VICTIMAS_AUTOPOSTULADOS_HOMBRES: registroTabla3.POSTS_RUV_HOMBRE_AUTO,
				OFERENTES_AUTOPOSTULADOS_MIGRANTES_VENEZOLANOS: null,
				OFERENTES_AUTOPOSTULADOS_MIGRANTES_VENEZOLANOS_MUJERES: null,
				OFERENTES_AUTOPOSTULADOS_MIGRANTES_VENEZOLANOS_HOMBRES: null,
				REMITIDOS_A_EMPLEADORES_SIN_AUTOPOSTULADOS_SISE_2_numero_de_hojas_de_vida_remitidas_a_empleadores_CV: (registroTabla3.POSTULACIONES_HOMBRE_ASISTIDA + registroTabla3.POSTULACIONES_HOMBRE_AUTO) + (registroTabla3.POSTULACIONES_MUJER_ASISTIDA + registroTabla3.POSTULACIONES_MUJER_AUTO),
				REMITIDOS_A_EMPLEADORES_SIN_AUTOPOSTULADOS_HOMBRES_SISE_2_1_numero_de_hojas_de_vida_remitidas_a_empleadores_hombres_CV: registroTabla3.POSTULACIONES_HOMBRE_ASISTIDA + registroTabla3.POSTULACIONES_HOMBRE_AUTO,
				_REMITIDOS_A_EMPLEADORES_SIN_AUTOPOSTULADOS_MUJERES_SISE_2_2_numero_de_hojas_de_vida_remitidas_a_empleadores_mujeres_CV: registroTabla3.POSTULACIONES_MUJER_ASISTIDA + registroTabla3.POSTULACIONES_MUJER_AUTO,
				HOJAS_DE_VIDA_REMITIDAS_DIRECTAMENTE_POR_EL_PUNTO_DE_ATENCIoN: registroTabla3.POSTULACIONES_MUJER_ASISTIDA + registroTabla3.POSTULACIONES_HOMBRE_ASISTIDA,
				HOJAS_DE_VIDA_REMITIDAS_DIRECTAMENTE_POR_EL_PUNTO_DE_ATENCIoN_HOMBRES: registroTabla3.POSTULACIONES_HOMBRE_ASISTIDA,
				HOJAS_DE_VIDA_REMITIDAS_DIRECTAMENTE_POR_EL_PUNTO_DE_ATENCIoN_MUJERES: registroTabla3.POSTULACIONES_MUJER_ASISTIDA,
				REMITIDOS_POR_EL_PUNTO_DE_ATENCIoN_TOTAL_SISE: (registroTabla3.POSTULACIONES_HOMBRE_ASISTIDA + registroTabla3.POSTULACIONES_HOMBRE_AUTO) + (registroTabla3.POSTULACIONES_MUJER_ASISTIDA + registroTabla3.POSTULACIONES_MUJER_AUTO),
				REMITIDOS_POR_AUTOPOSTULACIoN_ASISTIDA_TOTAL_SISE_2_numero_de_hojas_de_vida_remitidas_a_empleadores_CV: (registroTabla3.POSTULACIONES_HOMBRE_ASISTIDA + registroTabla3.POSTULACIONES_HOMBRE_AUTO) + (registroTabla3.POSTULACIONES_MUJER_ASISTIDA + registroTabla3.POSTULACIONES_MUJER_AUTO),

				TOTAL_REMISIONES_A_EMPLEADORES_VICTIMAS: (registroTabla3.POSTS_RUV_MUJER_ASISTIDA + registroTabla3.POSTS_RUV_MUJER_AUTO) + (registroTabla3.POSTS_RUV_HOMBRE_ASISTIDA + registroTabla3.POSTS_RUV_HOMBRE_AUTO),
				TOTAL_REMISIONES_A_EMPLEADORES_VICTIMAS_MUJERES: registroTabla3.POSTS_RUV_MUJER_ASISTIDA + registroTabla3.POSTS_RUV_MUJER_AUTO,
				TOTAL_REMISIONES_A_EMPLEADORES_VICTIMAS_HOMBRES: registroTabla3.POSTS_RUV_HOMBRE_ASISTIDA + registroTabla3.POSTS_RUV_HOMBRE_AUTO,
				REMISIONES_A_EMPLEADORES_VICTIMAS: registroTabla3.POSTS_RUV_MUJER_ASISTIDA + registroTabla3.POSTS_RUV_HOMBRE_ASISTIDA,
				REMISIONES_A_EMPLEADORES_VICTIMAS_MUJERES: registroTabla3.POSTS_RUV_MUJER_ASISTIDA,
				REMISIONES_A_EMPLEADORES_VICTIMAS_HOMBRES: registroTabla3.POSTS_RUV_HOMBRE_ASISTIDA,

				TOTAL_REMISIONES_A_EMPLEADORES_PCD: (registroTabla3.POSTS_PCD_MUJER_ASISTIDA + registroTabla3.POSTS_PCD_MUJER_AUTO) + (registroTabla3.POSTS_PCD_HOMBRE_ASISTIDA + registroTabla3.POSTS_PCD_HOMBRE_AUTO),
				TOTAL_REMISIONES_A_EMPLEADORES_PCD_MUJERES: registroTabla3.POSTS_PCD_MUJER_ASISTIDA + registroTabla3.POSTS_PCD_MUJER_AUTO,
				TOTAL_REMISIONES_A_EMPLEADORES_PCD_HOMBRES: registroTabla3.POSTS_PCD_HOMBRE_ASISTIDA + registroTabla3.POSTS_PCD_HOMBRE_AUTO,
				REMISIONES_A_EMPLEADORES_PCD: registroTabla3.POSTS_PCD_MUJER_ASISTIDA + registroTabla3.POSTS_PCD_HOMBRE_ASISTIDA,
				REMISIONES_A_EMPLEADORES_PCD_HOMBRES: registroTabla3.POSTS_PCD_HOMBRE_ASISTIDA,
				REMISIONES_A_EMPLEADORES_PCD_MUJERES: registroTabla3.POSTS_PCD_MUJER_ASISTIDA,
				REMISIONES_A_EMPLEADORES_PCD_HOMBRES: registroTabla3.POSTS_PCD_HOMBRE_ASISTIDA,

				TOTAL_REMISIONES_A_EMPLEADORES_DE_18_A_28_AÑOS: (registroTabla3.POSTS_JOVENES_MUJER_ASISTIDA + registroTabla3.POSTS_JOVENES_MUJER_AUTO) + (registroTabla3.POSTS_JOVENES_HOMBRE_ASISTIDA + registroTabla3.POSTS_JOVENES_HOMBRE_AUTO),
				TOTAL_REMISIONES_A_EMPLEADORES_DE_18_A_28_AÑOS_MUJERES: registroTabla3.POSTS_JOVENES_MUJER_ASISTIDA + registroTabla3.POSTS_JOVENES_MUJER_AUTO,
				TOTAL_REMISIONES_A_EMPLEADORES_DE_18_A_28_AÑOS_HOMBRES: registroTabla3.POSTS_JOVENES_HOMBRE_ASISTIDA + registroTabla3.POSTS_JOVENES_HOMBRE_AUTO,
				REMISIONES_A_EMPLEADORES_DE_18_A_28_AÑOS: registroTabla3.POSTS_JOVENES_MUJER_ASISTIDA + registroTabla3.POSTS_JOVENES_HOMBRE_ASISTIDA,
				REMISIONES_A_EMPLEADORES_DE_18_A_28_AÑOS_MUJERES: registroTabla3.POSTS_JOVENES_MUJER_ASISTIDA,
				REMISIONES_A_EMPLEADORES_DE_18_A_28_AÑOS_HOMBRES: registroTabla3.POSTS_JOVENES_HOMBRE_ASISTIDA,
				TOTAL_REMISIONES_A_EMPLEADORES_MIGRANTES_VENEZOLANOS: null,
				TOTAL_REMISIONES_A_EMPLEADORES_MIGRANTES_VENEZOLANOS_MUJERES: null,
				TOTAL_REMISIONES_A_EMPLEADORES_MIGRANTES_VENEZOLANOS_HOMBRES: null,
				REMISIONES_A_EMPLEADORES_MIGRANTES_VENEZOLANOS: null,
				REMISIONES_A_EMPLEADORES_MIGRANTES_VENEZOLANOS_MUJERES: null,
				REMISIONES_A_EMPLEADORES_MIGRANTES_VENEZOLANOS_HOMBRES: null,
				REMISIONES_A_EMPLEADORES_ETNICOS: null,
				REMISIONES_A_EMPLEADORES_ETNICOS_MUJERES: null,
				REMISIONES_A_EMPLEADORES_ETNICOS_HOMBRES: null,
				TOTAL_COLOCADOS_SISE_3_numero_de_personas_colocadas_CV: registroTabla3.COLOCACIONES_MUJER + registroTabla3.COLOCACIONES_HOMBRE,
				COLOCADOS_ENTRADAS_SISE_3_numero_de_personas_colocadas_CV: registroTabla3.COLOCACIONES_MUJER + registroTabla3.COLOCACIONES_HOMBRE,
				COLOCADOS_DEVUELTOS_SISE: null,
				COLOCADOS_HOMBRES_SISE_3_1_numero_de_personas_colocadas_hombres_CV: registroTabla3.COLOCACIONES_HOMBRE,
				COLOCADOS_MUJERES_SISE_3_2_numero_de_personas_colocadas_mujeres_CV: registroTabla3.COLOCACIONES_MUJER,
				COLOCADOS_DIRECTOS_SISE_3_numero_de_personas_colocadas_CV: registroTabla3.COLOCACIONES_MUJER + registroTabla3.COLOCACIONES_HOMBRE,
				COLOCADOS_DIRECTOS_HOMBRES_SISE_3_1_numero_de_personas_colocadas_hombres_CV: registroTabla3.COLOCACIONES_HOMBRE,
				COLOCADOS_DIRECTOS_MUJERES_SISE_3_2_numero_de_personas_colocadas_mujeres_CV: registroTabla3.COLOCACIONES_MUJER,
				COLOCADOS_INDIRECTOS_SISE: null,
				COLOCADOS_INDIRECTOS_HOMBRES_SISE: null,
				COLOCADOS_INDIRECTOS_MUJERES_SISE: null,
				COLOCADOS_DIRECTOS_VICTIMAS_SISE: registroTabla3.COLOCACIONES_RUV_MUJER + registroTabla3.COLOCACIONES_RUV_HOMBRE,
				COLOCADOS_DIRECTOS_VICTIMAS_MUJERES_SISE: registroTabla3.COLOCACIONES_RUV_MUJER,
				COLOCADOS_DIRECTOS_VICTIMAS_HOMBRES_SISE: registroTabla3.COLOCACIONES_RUV_HOMBRE,
				COLOCADOS_DIRECTOS_PcD_SISE: registroTabla3.COLOCACIONES_PCD_MUJER + registroTabla3.COLOCACIONES_PCD_HOMBRE,
				COLOCADOS_DIRECTOS_PcD_MUJERES_SISE: registroTabla3.COLOCACIONES_PCD_MUJER,
				COLOCADOS_DIRECTOS_PcD_HOMBRES_SISE: registroTabla3.COLOCACIONES_PCD_HOMBRE,
				COLOCADOS_DIRECTOS_18_A_28_AÑOS_SISE: registroTabla3.COLOCACIONES_JOVENES_MUJER + registroTabla3.COLOCACIONES_JOVENES_HOMBRE,
				COLOCADOS_DIRECTOS_18_A_28_AÑOS_MUJERES_SISE: registroTabla3.COLOCACIONES_JOVENES_MUJER,
				COLOCADOS_DIRECTOS_18_A_28_AÑOS_HOMBRES_SISE: registroTabla3.COLOCACIONES_JOVENES_HOMBRE,
				COLOCADOS_DIRECTOS_MIGRANTES_VENEZOLANOS: null,
				COLOCADOS_DIRECTOS_MIGRANTES_VENEZOLANOS_MUJERES: null,
				COLOCADOS_DIRECTOS_MIGRANTES_VENEZOLANOS_HOMBRE: null,
				COLOCADOS_DIRECTOS_ETNICOS: null,
				COLOCADOS_DIRECTOS_ETNICOS_MUJERES: null,
				COLOCADOS_DIRECTOS_ETNICOS_HOMBRES: null,
				SEDES_INSCRITAS_TOTAL_NETO_SISE_4_numero_de_empleadores_registrados_inscritos_CV: registroTabla3.EMPRESAS,
				SEDES_INSCRITAS_ENTRADAS_SISE_4_numero_de_empleadores_registrados_inscritos_CV: registroTabla3.EMPRESAS,
				SEDES_INSCRITAS_SALIDAS_SISE: registroTabla3.EMPRESAS,
				EMPRESAS_INSCRITAS_SISE_4_numero_de_empleadores_registrados_inscritos_CV: registroTabla3.EMPRESAS,
				DIRECCIONAMIENTOS_INDIVIDUALES_DE_ORIENTACIoN_LABORAL_REALIZADOS_SISE_5_numero_de_personas_atendidas_en_entrevistas_de_orientacion_ocupacional_CV: registroTabla3.ORIENTADOS_HOMBRE_IND + registroTabla3.ORIENTADOS_MUJER_IND,
				DIRECCIONAMIENTOS_INDIVIDUALES_DE_ORIENTACIoN_LABORAL_REALIZADOS_HOMBRES_SISE_5_1_numero_de_personas_atendidas_en_entrevistas_de_orientacion_ocupacional_hombres_CV: registroTabla3.ORIENTADOS_HOMBRE_IND,
				DIRECCIONAMIENTOS_INDIVIDUALES_DE_ORIENTACIoN_LABORAL_REALIZADOS_MUJERES_SISE_5_2_numero_de_personas_atendidas_en_entrevistas_de_orientacion_ocupacional_mujeres_CV: registroTabla3.ORIENTADOS_MUJER_IND,
				VICTIMAS_DIRECCIONAMIENTOS_INDIVIDUALES_DE_ORIENTACIoN_LABORAL_SISE: registroTabla3.ORIENTADOS_RUV_MUJER_IND + registroTabla3.ORIENTADOS_RUV_HOMBRE_IND,
				VICTIMAS_DIRECCIONAMIENTOS_INDIVIDUALES_DE_ORIENTACIoN_LABORAL_Mujeres_SISE: registroTabla3.ORIENTADOS_RUV_MUJER_IND,
				VICTIMAS_DIRECCIONAMIENTOS_INDIVIDUALES_DE_ORIENTACIoN_LABORAL_Hombres_SISE: registroTabla3.ORIENTADOS_RUV_HOMBRE_IND,
				PCD_DIRECCIONAMIENTOS_INDIVIDUALES_DE_ORIENTACIoN_LABORAL_SISE: registroTabla3.ORIENTADOS_PCD_MUJER_IND + registroTabla3.ORIENTADOS_PCD_HOMBRE_IND,
				PCD_DIRECCIONAMIENTOS_INDIVIDUALES_DE_ORIENTACIoN_LABORAL_Mujeres_SISE: registroTabla3.ORIENTADOS_PCD_MUJER_IND,
				PCD_DIRECCIONAMIENTOS_INDIVIDUALES_DE_ORIENTACIoN_LABORAL_Hombres_SISE: registroTabla3.ORIENTADOS_PCD_HOMBRE_IND,
				_18_a_28_AÑOS_DIRECCIONAMIENTOS_INDIVIDUALES_DE_ORIENTACIoN_LABORAL_SISE: registroTabla3.ORIENTADOS_JOVENES_MUJER_IND + registroTabla3.ORIENTADOS_JOVENES_HOMBRE_IND,
				_18_a_28_AÑOS_DIRECCIONAMIENTOS_INDIVIDUALES_DE_ORIENTACIoN_LABORAL_Mujeres_SISE: registroTabla3.ORIENTADOS_JOVENES_MUJER_IND,
				_18_a_28_AÑOS_DIRECCIONAMIENTOS_INDIVIDUALES_DE_ORIENTACIoN_LABORAL_Hombres_SISE: registroTabla3.ORIENTADOS_JOVENES_HOMBRE_IND,
				MIGRANTES_VENEZOLANOS_DIRECCIONAMIENTOS_INDIVIDUALES_DE_ORIENTACIoN_LABORAL_SISE: null,
				MIGRANTES_VENEZOLANOS_DIRECCIONAMIENTOS_INDIVIDUALES_DE_ORIENTACIoN_LABORAL_Mujeres_SISE: null,
				MIGRANTES_VENEZOLANOS_DIRECCIONAMIENTOS_INDIVIDUALES_DE_ORIENTACIoN_LABORAL_Hombres_SISE: null,
				ETNICOS_DIRECCIONAMIENTOS_INDIVIDUALES_DE_ORIENTACIoN_LABORAL_SISE: null,
				ETNICOS_MUJERES_DIRECCIONAMIENTOS_INDIVIDUALES_DE_ORIENTACIoN_LABORAL_SISE: null,
				ETNICOS_HOMBRES_DIRECCIONAMIENTOS_INDIVIDUALES_DE_ORIENTACIoN_LABORAL_SISE: null,
				DIRECCIONAMIENTOS_GRUPALES_DE_ORIENTACIoN_LABORAL_REALIZADOS_SISE_6_numero_de_personas_atendidas_en_actividades_grupales_de_orientacion_ocupacional: registroTabla3.ORIENTADOS_HOMBRE_GRU + registroTabla3.ORIENTADOS_MUJER_GRU,
				DIRECCIONAMIENTOS_GRUPALES_DE_ORIENTACIoN_LABORAL_REALIZADOS_HOMBRES_SISE_6_1_numero_de_personas_atendidas_en_actividades_grupales_de_orientacion_ocupacional_hombres: registroTabla3.ORIENTADOS_HOMBRE_GRU,
				DIRECCIONAMIENTOS_GRUPALES_DE_ORIENTACIoN_LABORAL_REALIZADOS_MUJERES_SISE_6_2_numero_de_personas_atendidas_en_actividades_grupales_de_orientacion_ocupacional_mujeres: registroTabla3.ORIENTADOS_MUJER_GRU,
				DIRECCIONAMIENTOS_GRUPALES_DE_ORIENTACIoN_LABORAL_REALIZADOS_A_PERSONAS_18_a_28_AÑOS: registroTabla3.ORIENTADOS_JOVENES_MUJER_GRU + registroTabla3.ORIENTADOS_JOVENES_HOMBRE_GRU,
				DIRECCIONAMIENTOS_GRUPALES_DE_ORIENTACIoN_LABORAL_REALIZADOS_A_PERSONAS_18_a_28_AÑOS_MUJERES: registroTabla3.ORIENTADOS_JOVENES_MUJER_GRU,
				DIRECCIONAMIENTOS_GRUPALES_DE_ORIENTACIoN_LABORAL_REALIZADOS_A_PERSONAS_18_a_28_AÑOS_HOMBRES: registroTabla3.ORIENTADOS_JOVENES_HOMBRE_GRU,
				DIRECCIONAMIENTOS_GRUPALES_DE_ORIENTACIoN_LABORAL_REALIZADOS_A_PcD: registroTabla3.ORIENTADOS_PCD_MUJER_GRU + registroTabla3.ORIENTADOS_PCD_HOMBRE_GRU,
				DIRECCIONAMIENTOS_GRUPALES_DE_ORIENTACIoN_LABORAL_REALIZADOS_A_PcD_MUJERES: registroTabla3.ORIENTADOS_PCD_MUJER_GRU,
				DIRECCIONAMIENTOS_GRUPALES_DE_ORIENTACIoN_LABORAL_REALIZADOS_A_PcD_HOMBRES: registroTabla3.ORIENTADOS_PCD_HOMBRE_GRU,
				DIRECCIONAMIENTOS_GRUPALES_DE_ORIENTACIoN_LABORAL_REALIZADOS_A_VICTIMAS: registroTabla3.ORIENTADOS_RUV_MUJER_GRU + registroTabla3.ORIENTADOS_RUV_HOMBRE_GRU,
				DIRECCIONAMIENTOS_GRUPALES_DE_ORIENTACIoN_LABORAL_REALIZADOS_A_VICTIMAS_MUJERES: registroTabla3.ORIENTADOS_RUV_MUJER_GRU,
				DIRECCIONAMIENTOS_GRUPALES_DE_ORIENTACIoN_LABORAL_REALIZADOS_A_VICTIMAS_HOMBRES: registroTabla3.ORIENTADOS_RUV_HOMBRE_GRU,
				DIRECCIONAMIENTOS_GRUPALES_DE_ORIENTACIoN_LABORAL_REALIZADOS_A_Migrantes_Venezolanos: null,
				DIRECCIONAMIENTOS_GRUPALES_DE_ORIENTACIoN_LABORAL_REALIZADOS_A_Migrantes_Venezolanos_MUJERES: null,
				DIRECCIONAMIENTOS_GRUPALES_DE_ORIENTACIoN_LABORAL_REALIZADOS_A_Migrantes_Venezolanos_HOMBRES: null,
				DIRECCIONAMIENTOS_GRUPALES_DE_ORIENTACIoN_LABORAL_REALIZADOS_A_ETNICOS: null,
				DIRECCIONAMIENTOS_GRUPALES_DE_ORIENTACIoN_LABORAL_REALIZADOS_A_ETNICOS_MUJERES: null,
				DIRECCIONAMIENTOS_GRUPALES_DE_ORIENTACIoN_LABORAL_REALIZADOS_A_ETNICOS_HOMBRES: null,
				DIRECCIONAMIENTOS_A_FORMACIoN_PARA_EL_TRABAJO_SISE_7_numero_de_personas_direccionadas_a_programas_de_formacion_y_capacitacion_para_el_trabajo: null,
				_7_1_numero_de_personas_direccionadas_a_programas_de_formacion_y_capacitacion_para_el_trabajo_hombres: null,
				_7_1_1_numero_de_personas_direccionadas_a_programas_de_formacion_en_competencias_claves_y_transversales_hombres: null,
				_7_1_2_numero_de_personas_direccionadas_a_programas_de_formacion_en_tecnologias_de_la_informacion_y_las_comunicaciones_tic_hombres: null,
				_7_1_3_numero_de_personas_direccionadas_a_programas_de_alfabetizacion_o_bachillerato_hombres: null,
				_7_1_4_numero_de_personas_direccionadas_a_programas_de_entrenamiento_o_reentrenamiento_tecnico_hombres: null,
				_7_1_5_numero_de_personas_direccionadas_a_programas_de_tecnico_laboral_hombres: null,
				_7_2_numero_de_personas_direccionadas_a_programas_de_formacion_y_capacitacion_para_el_trabajo_mujeres: null,
				_7_2_1_numero_de_personas_direccionadas_a_programas_de_formacion_en_competencias_claves_y_transversales_mujeres: null,
				_7_2_2_numero_de_personas_direccionadas_a_programas_de_formacion_en_tecnologias_de_la_informacion_y_las_comunicaciones_tic_mujeres: null,
				_7_2_3_numero_de_personas_direccionadas_a_programas_de_alfabetizacion_o_bachillerato_mujeres: null,
				_7_2_4_numero_de_personas_direccionadas_a_programas_de_entrenamiento_o_reentrenamiento_tecnico_mujeres: null,
				_7_2_5_numero_de_personas_direccionadas_a_programas_de_tecnico_laboral_mujeres: null,
				DIRECCIONAMIENTOS_A_FORMACIoN_PARA_EL_TRABAJO_REALIZADOS_SISE_8_numero_de_personas_que_culminaron_programas_de_formacion_y_capacitacion_para_el_trabajo: null,
				_8_1_numero_de_personas_que_culminaron_programas_de_formacion_y_capacitacion_para_el_trabajo_hombres: null,
				_8_1_1_numero_de_personas_que_culminaron_programas_de_formacion_en_competencias_claves_y_transversales_hombres: null,
				_8_1_2_numero_de_personas_que_culminaron_programas_de_formacion_en_tecnologias_de_la_informacion_y_las_comunicaciones_tic_hombres: null,
				_8_1_3_numero_de_personas_que_culminaron_programas_de_alfabetizacion_o_bachillerato_hombres: null,
				_8_1_4_numero_de_personas_que_culminaron_programas_de_entrenamiento_o_reentrenamiento_tecnico_hombres: null,
				_8_1_5_numero_de_personas_que_culminaron_programas_de_tecnico_laboral_hombres: null,
				_8_2_numero_de_personas_que_culminaron_programas_de_formacion_y_capacitacion_para_el_trabajo_mujeres: null,
				_8_2_1_numero_de_personas_que_culminaron_programas_de_formacion_en_competencias_claves_y_transversales_mujeres: null,
				_8_2_2_numero_de_personas_que_culminaron_programas_de_formacion_en_tecnologias_de_la_informacion_y_las_comunicaciones_tic_mujeres: null,
				_8_2_3_numero_de_personas_que_culminaron_programas_de_alfabetizacion_o_bachillerato_mujeres: null,
				_8_2_4_numero_de_personas_que_culminaron_programas_de_entrenamiento_o_reentrenamiento_tecnico_mujeres: null,
				_8_2_5_numero_de_personas_que_culminaron_programas_de_tecnico_laboral_mujeres: null,
				DIRECCIONAMIENTOS_A_EMPRENDIMIENTO_SISE_9_numero_de_personas_direccionadas_a_programas_de_emprendimiento: null,
				_9_1_numero_de_personas_direccionadas_a_programas_de_emprendimiento_hombres: null,
				_9_2_numero_de_personas_direccionadas_a_programas_de_emprendimiento_mujeres: null,
				_10_numero_de_pqrs_radicados_en_el_punto_de_atencion: null,
				VACANTES_REGISTRADAS_TOTAL_SISE_Datos_hasta_abril_de_2017_por_CV_: null,
				PUESTOS_DE_TRABAJO_SISE_Datos_hasta_abril_de_2017_por_CV_: null,
				PUESTOS_DE_TRABAJO_CON_GESTIoN_SISE_Datos_desde_junio_de_2017_: null,
				PUESTOS_DE_TRABAJO_SIN_GESTIoN_SISE_Datos_desde_junio_de_2017_: null,
				TIPO_CAJA: null, // Preguntar
				TIPO_PUNTO_ATEN: tablaBase.tipo_de_punto_de_atencion || null,
				TERCERO_DE_UN_ENTE: null,
			};

			registrosFinales.push(registroFinal);
		}

    }

    return registrosFinales;
};

module.exports = { fetchConsolidadoData }